---
title: "Kenya's Rangelands Protected Areas"
author: "Isaac Mureithi"
date: "2025-04-01"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r}
# Load libraries

if (!require("pacman")) install.packages("pacman")

pacman::p_load(sf, terra, tidyverse, tidyterra, colorspace, ggrepel, patchwork, tmap, trend, slider, forcats, viridis, scales, hexbin)
```

```{r}
# Set theme for plots

theme_beautiful <- function() {
  theme_bw() +
    theme(
      text = element_text(family = "Helvetica"),
      axis.text = element_text(size = 8, color = "black"),
      axis.title = element_text(size = 8, color = "black"),
      axis.line.x = element_line(linewidth = 0.3, color = "black"), # Use linewidth
      axis.line.y = element_line(linewidth = 0.3, color = "black"), # Use linewidth
      axis.ticks = element_line(linewidth = 0.3, color = "black"), # Use linewidth
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.y = element_blank(),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm"),
      plot.title = element_text(
        size = 8,
        vjust = 1,
        hjust = 0.5,
        color = "black"
      ),
      legend.text = element_text(size = 8, color = "black"),
      legend.title = element_text(size = 8, color = "black"),
      legend.position = "right", # Move legend to the right
      legend.key.size = unit(0.9, "line"),
      legend.background = element_rect(
        color = "black",
        fill = "transparent",
        linewidth = 0.3, # Use linewidth
        linetype = "blank"
      )
    )
}

# Attempt to set the Helvetica font (may not work on all systems)
if (Sys.info()[["sysname"]] == "Windows") {
  windowsFonts("Helvetica" = windowsFont("Helvetica"))
}
```

```{r}
# World Map Import

Global.Country.Boundaries <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/2.Kenya-s-Rangelands-Protected-Areas_files/additional_data_layers_wgs84/global_country_boundaries_simplified_wgs84.shp")
```

```{r}
# Plot of World Map

ggplot() +
  geom_sf(data = Global.Country.Boundaries)+
  labs(title = "World Country Map")+
  theme_beautiful()
```

```{r}
# Africa Country Boundary import

Africa.Country.Boundaries <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/2.Kenya-s-Rangelands-Protected-Areas_files/additional_data_layers_wgs84/africa_country_boundaries_simplified_wgs84.shp")
```

```{r}
# Focusing on Eastern Africa

Eastern.Africa.Country.ISOCodes <- c("BI", "DJ", "ER", "ET", "KE", "RW", "SO", "TZ", "UG")
Eastern.Africa.Data <- Africa.Country.Boundaries %>% 
  filter(ISO_Code %in% Eastern.Africa.Country.ISOCodes)
```

```{r}
# Plotting with a focus on Eastern Africa

ggplot() +
  geom_sf(data = Global.Country.Boundaries, fill = "white", colour = "grey") +
  geom_sf(data = Africa.Country.Boundaries, aes(fill = "Africa"), colour = "grey", alpha = 0.5) +
  geom_sf(data = Eastern.Africa.Data, aes(fill = "Eastern Africa"), colour = "black") +
  scale_fill_manual(values = c("Africa" = "lightgreen", "Eastern Africa" = "darkgreen"),
                    name = "Region",labels = c("Africa", "Eastern Africa")) +
  labs(title = "Eastern Africa in World Map")+
  theme_beautiful()
```

```{r}
#Focusing on Kenya

  Kenya.Admin.Boundary <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/2.Kenya-s-Rangelands-Protected-Areas_files/additional_data_layers_wgs84/kenya_admin_boundary_wgs84.shp")
```

```{r}
# Plotting Kenya

ggplot() +
  geom_sf(data = Eastern.Africa.Data, aes(fill = "Eastern Africa"), alpha = 0.5, colour = NA) +
  geom_sf(data = Kenya.Admin.Boundary, aes(fill = "Kenya"), colour = "black") +
  scale_fill_manual(name = "Region",values = c("Eastern Africa" = "darkgreen", "Kenya" = "lightgreen"))+
  labs(title = "Kenya Administrative Boundary") +
  theme_beautiful()
```

```{r}
#Focusing on Boundaries within Kenya

Kenya.Regional.Admin.Boundary <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/2.Kenya-s-Rangelands-Protected-Areas_files/additional_data_layers_wgs84/kenya_regional_admin1_boundary_wgs84.shp")
```

```{r}
# Plotting Kenya's Regional Boundaries

ggplot()+
  geom_sf(data = Kenya.Admin.Boundary, colour = "black")+
  geom_sf(data = Kenya.Regional.Admin.Boundary, colour = "grey50")+
  labs(title = "Kenya's Subregional Administrative Boundaries") +
  theme_beautiful()
```

```{r}
# Focusing on Kenya's Terrestrial Protected Areas

Kenya.Terrestrial.PAs <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/2.Kenya-s-Rangelands-Protected-Areas_files/additional_data_layers_wgs84/kenya_terrestrial_protected_areas_wgs84.shp")
```

```{r}
# Plotting Kenya's Terrestrial PAs

ggplot()+
  geom_sf(data = Kenya.Admin.Boundary, colour = "black")+
  geom_sf(data = Kenya.Regional.Admin.Boundary, colour = "grey50")+
  geom_sf(data = Kenya.Terrestrial.PAs, aes(fill = "Protected Areas"), alpha = 0.5)+
  scale_fill_manual(values = c("Protected Areas" = "brown"),name = "Legend",labels = c("Protected Areas")) +
  labs(title = "Kenya's Terrestrial Protected Areas") +
  theme_beautiful()
```

```{r}
# Focusing on Kenya's Rangelands (80& of Kenya's LandMass)

Rangeland.Counties <- c("Marsabit", "Isiolo", "Meru", "Tharaka-Nithi", "Embu", 
                        "Kitui", "Makueni", "Tana River", "Lamu", "Taita Taveta",
                        "Garissa", "Wajir", "Mandera", "Turkana", "West Pokot",
                        "Samburu", "Baringo", "Laikipia", "Narok", "Kajiado")

Kenya.Rangeland.Counties <- Kenya.Regional.Admin.Boundary %>% 
  filter(ADM1_EN %in% Rangeland.Counties)
```

```{r}
# Plotting the Rangeland Counties

tmap_mode("plot")

Kenya.Rangeland.Map <-
  tm_shape(Kenya.Regional.Admin.Boundary) +
  tm_borders(col = "grey70", lwd = 0.5) +
  tm_shape(Kenya.Rangeland.Counties) +
  # Reverting to 'col' for the constant fill color, as 'fill' seems to be for mapped variables (I am struggling to understand tmap v3 and tmap v4) - 'alpha' is still used for constant transparency.
  tm_fill(
    col = "lightgrey",   
    alpha = 1,           
    legend.show = TRUE,
    legend.title = "Rangeland Counties") +
  tm_borders(col = "black", lwd = 1) +
  tm_shape(Kenya.Admin.Boundary) +
  tm_borders(col = "black", lwd = 1.2) +
  tm_layout(
    title.size = 1,
    legend.text.size = 0.8,
    legend.title.size = 0.9,
    legend.position = c("right", "bottom"),
    frame = FALSE,
    text.fontfamily = "Helvetica") +
  tm_title("Kenya's Rangeland Counties")

Kenya.Rangeland.Map
```

```{r}
# Importing RPI Datasets - Rasters (TIFs)

Actual.GPP <- rast("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/2.Kenya-s-Rangelands-Protected-Areas_files/RPI Datasets (GuyLomax)/actual_gpp_ea_v2.tif")

Potential.GPP <- rast("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/2.Kenya-s-Rangelands-Protected-Areas_files/RPI Datasets (GuyLomax)/potential_gpp_ea_v2.tif")

RPI <- rast("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/2.Kenya-s-Rangelands-Protected-Areas_files/RPI Datasets (GuyLomax)/rpi_ea_v2.tif")
```

```{r}
# MAPS SOURCED FROM WDPA

# "UNEP-WCMC and IUCN (2025), Protected Planet: The World Database on Protected Areas (WDPA) and World Database on Other Effective Area-based Conservation Measures (WD-OECM) [Online], April 2025, Cambridge, UK: UNEP-WCMC and IUCN. Available at: www.protectedplanet.net." 
```

```{r}
# Importing National Parks & National Reserves (GAE/TCA)

Amboseli <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/National Parks&Reserves/Amboseli-WDPA_WDOECM_Apr2025_Public_758_shp/WDPA_WDOECM_Apr2025_Public_758_shp_0/WDPA_WDOECM_Apr2025_Public_758_shp-polygons.shp")

ChyuluHills <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/National Parks&Reserves/ChyuluHills-WDPA_WDOECM_Apr2025_Public_19563_shp/WDPA_WDOECM_Apr2025_Public_19563_shp_0/WDPA_WDOECM_Apr2025_Public_19563_shp-polygons.shp")

TsavoWest <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/National Parks&Reserves/TsavoWest-WDPA_WDOECM_Apr2025_Public_19564_shp/WDPA_WDOECM_Apr2025_Public_19564_shp_0/WDPA_WDOECM_Apr2025_Public_19564_shp-polygons.shp")

TsavoEast <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/National Parks&Reserves/TsavoEast-WDPA_WDOECM_Apr2025_Public_752_shp/WDPA_WDOECM_Apr2025_Public_752_shp_0/WDPA_WDOECM_Apr2025_Public_752_shp-polygons.shp")

NgaiNdethia <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/National Parks&Reserves/NgaiNdethia-WDPA_WDOECM_Apr2025_Public_2595_shp/WDPA_WDOECM_Apr2025_Public_2595_shp_0/WDPA_WDOECM_Apr2025_Public_2595_shp-polygons.shp")

SouthKitui <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/National Parks&Reserves/SouthKitui-WDPA_WDOECM_Apr2025_Public_2590_shp/WDPA_WDOECM_Apr2025_Public_2590_shp_0/WDPA_WDOECM_Apr2025_Public_2590_shp-polygons.shp")
```

```{r}
# Visualising GAE/TCA

#ggplot() +
#  geom_sf(data = Amboseli, aes(fill = NAME), color = "black", linewidth = 0.3) +
#  geom_sf(data = ChyuluHills, aes(fill = NAME), color = "black", linewidth = 0.3) +
#  geom_sf(data = TsavoEast, aes(fill = NAME), color = "black", linewidth = 0.3) +
#  geom_sf(data = TsavoWest, aes(fill = NAME), color = "black", linewidth = 0.3) +
#  geom_sf(data = NgaiNdethia, aes(fill = NAME), color = "black", linewidth = 0.3) +
#  geom_sf(data = SouthKitui, aes(fill = NAME), color = "black", linewidth = 0.3) +
#  labs(title = "National Parks and Reserves - GAE/TCA", fill = "Protected Area") +
#  theme_beautiful()

GAE.TCA <- bind_rows(
  Amboseli,
  ChyuluHills,
  TsavoEast,
  TsavoWest,
  NgaiNdethia,
  SouthKitui
) %>%
  mutate(Area = NAME)  # standardize the column


tmap_mode("view")  # or "plot" for static

tm_shape(GAE.TCA) +
  tm_polygons(
    fill = "Area",
    fill.scale = tm_scale_categorical(values = "brewer.set3"),
    fill.legend = tm_legend(title = "Protected Area"),
    col = "black", lwd = 0.5
  ) +
  tm_title("National Parks and Reserves - GAE/TCA")
```

```{r}
# Importing Community Conservancies & Group Ranches

AET.Conservancies <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/5. AET-Conservancies/AET_Conservancies.shp")

AET.Buffers <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/5. AET-Conservancies/AET_Other_Conserved_Areas.shp")

DawidaRanch_T <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/Community&Groups/DawidaRanch(T)-WDPA_WDOECM_Apr2025_Public_72297_shp/WDPA_WDOECM_Apr2025_Public_72297_shp_0/WDPA_WDOECM_Apr2025_Public_72297_shp-points.shp")

Kasigau_T <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/Community&Groups/Kasigau(T)-WDPA_WDOECM_Apr2025_Public_7582_shp/WDPA_WDOECM_Apr2025_Public_7582_shp_0/WDPA_WDOECM_Apr2025_Public_7582_shp-polygons.shp")

MbuliaGroupRanch_T <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/Community&Groups/MbuliaGroupRanch(T)-WDPA_WDOECM_Apr2025_Public_72293_shp/WDPA_WDOECM_Apr2025_Public_72293_shp_0/WDPA_WDOECM_Apr2025_Public_72293_shp-points.shp")

Mnjonyi_T <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/Community&Groups/Mnjonyi(T)-WDPA_WDOECM_Apr2025_Public_555785981_shp/WDPA_WDOECM_Apr2025_Public_555785981_shp_0/WDPA_WDOECM_Apr2025_Public_555785981_shp-polygons.shp")

Mwaganini_T <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/Community&Groups/Mwaganini(T)-WDPA_WDOECM_Apr2025_Public_555785983_shp/WDPA_WDOECM_Apr2025_Public_555785983_shp_0/WDPA_WDOECM_Apr2025_Public_555785983_shp-polygons.shp")

Ronge_T <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/Community&Groups/Ronge(T)-WDPA_WDOECM_Apr2025_Public_555785982_shp/WDPA_WDOECM_Apr2025_Public_555785982_shp_0/WDPA_WDOECM_Apr2025_Public_555785982_shp-polygons.shp")

TaitaHills_T <- st_read("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/4.WDPA-GAE&TSAVOs/Community&Groups/TaitaHills(T)-WDPA_WDOECM_Apr2025_Public_7408_shp/WDPA_WDOECM_Apr2025_Public_7408_shp_0/WDPA_WDOECM_Apr2025_Public_7408_shp-polygons.shp")
```

```{r}
# Visualising the Community Conservancies & Group Ranches within GAE/TCA

ggplot()+
  geom_sf(data = AET.Conservancies, aes(fill = consv_name), color = "black", linewidth = 0.1) +
  geom_sf(data = AET.Buffers, aes(fill = consv_name), color = "black", linewidth = 0.1) +
  geom_sf(data = DawidaRanch_T, aes(fill = NAME), color = 'black', linewidth = 0.1) +
  geom_sf(data = Kasigau_T, aes(fill = NAME), color = 'black', linewidth = 0.1) +
  geom_sf(data = Mnjonyi_T, aes(fill = NAME), color = 'black', linewidth = 0.1) +
  geom_sf(data = MbuliaGroupRanch_T, aes(fill = NAME), color = 'black', linewidth = 0.1) +
  geom_sf(data = Mwaganini_T, aes(fill = NAME), color = 'black', linewidth = 0.1) +
  geom_sf(data = Ronge_T, aes(fill = NAME), color = 'black', linewidth = 0.1) +
  geom_sf(data = TaitaHills_T, aes(fill = NAME), color = 'black', linewidth = 0.1) +
  labs(title = "Community & Group Ranches in GAE/TCA") +
  theme_beautiful()
```

```{r}
# Visualising the Community & Group Lands surrounding Amboseli NP

ggplot()+
  geom_sf(data = Amboseli, aes(fill = NAME), color = "black", linewidth = 0.3) +
  geom_sf(data = AET.Conservancies, aes(fill = consv_name), color = "black", linewidth = 0.1) +
  labs(title = "Community & Group Lands surrounding Amboseli NP") +
  theme_beautiful()
```

```{r}
# Visualising the Community & Group Rangelands/Grazelands/Buffers surrounding Amboseli NP

ggplot()+
 geom_sf(data = Amboseli, aes(fill = NAME), color = "black", linewidth = 0.3) +
  geom_sf(data = AET.Buffers, aes(fill = consv_name), color = "black", linewidth = 0.1) +
  labs(title = "Bufferzones, Corridors & Grazelands surrounding Amboseli NP") +
  theme_beautiful()
```

```{r}
## Visualising AET.Conservancies and AET.Buffers in one map to show Connectivity

# Add a category column to both layers
AET.Conservancies <- AET.Conservancies %>%
  mutate(ZoneType = "Conservancy")

AET.Buffers <- AET.Buffers %>%
  mutate(ZoneType = "Buffer")

# Combine both layers into one
AET.AllZones <- bind_rows(AET.Conservancies, AET.Buffers)

# Plotting the combined AET zones
tmap_mode("view")
tm_shape(AET.AllZones) +
  tm_polygons(
    fill = "ZoneType",
    fill.scale = tm_scale_categorical(values = c("Buffer" = "forestgreen", "Conservancy" = "limegreen")),
    fill.legend = tm_legend(title = "AET Areas"),
    col = "black", lwd = 0.4
  ) +
  tm_title ("Connectivity of AET Conservancies and Buffers")
```

```{r}
# Visualising RPI for each Area
```

```{r}
## Visualising Amboseli NP

Amboseli.RPI.Mask <- mask(RPI, Amboseli)
Amboseli.RPI.Crop <- crop(Amboseli.RPI.Mask, Amboseli)

# Averaging across years for visualization
Amboseli.RPI.Mean <- mean(Amboseli.RPI.Crop, na.rm = TRUE)

# Visualise
tmap_mode("view")
tm_shape(Amboseli.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"), 
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(Amboseli) +
  tm_borders(col = "white", lwd = 2) +
  tm_title("Spatial Distribution of Mean RPI in Amboseli NP") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Visualising Tsavo East NP

TsavoEast.RPI.Mask <- mask(RPI, TsavoEast)
TsavoEast.RPI.Crop <- crop(TsavoEast.RPI.Mask, TsavoEast)

# Averaging across years for visualization
TsavoEast.RPI.Mean <- mean(TsavoEast.RPI.Crop, na.rm = TRUE)

# Visualise
tmap_mode("view")
tm_shape(TsavoEast.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"), 
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(TsavoEast) +
  tm_borders(col = "white", lwd = 2) +
  tm_title("Spatial Distribution of Mean RPI in Tsavo East NP") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Visualising Tsavo West NP

TsavoWest.RPI.Mask <- mask(RPI, TsavoWest)
TsavoWest.RPI.Crop <- crop(TsavoWest.RPI.Mask, TsavoWest)

# Averaging across years for visualization
TsavoWest.RPI.Mean <- mean(TsavoWest.RPI.Crop, na.rm = TRUE)

# Visualise
tmap_mode("view")
tm_shape(TsavoWest.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"), 
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(TsavoWest) +
  tm_borders(col = "white", lwd = 2) +
  tm_title("Spatial Distribution of Mean RPI in Tsavo West NP") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Visualising Chyulu Hills NP

ChyuluHills.RPI.Mask <- mask(RPI, ChyuluHills)
ChyuluHills.RPI.Crop <- crop(ChyuluHills.RPI.Mask, ChyuluHills)

# Averaging across years for visualization
ChyuluHills.RPI.Mean <- mean(ChyuluHills.RPI.Crop, na.rm = TRUE)

# Visualise
tmap_mode("view")
tm_shape(ChyuluHills.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"), 
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(ChyuluHills) +
  tm_borders(col = "white", lwd = 2) +
  tm_title("Spatial Distribution of Mean RPI in Chyulu Hills NP") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Visualising Ngai Ndethia NR

NgaiNdethia.RPI.Mask <- mask(RPI, NgaiNdethia)
NgaiNdethia.RPI.Crop <- crop(NgaiNdethia.RPI.Mask, NgaiNdethia)

# Averaging across years for visualization
NgaiNdethia.RPI.Mean <- mean(NgaiNdethia.RPI.Crop, na.rm = TRUE)

# Visualise
tmap_mode("view")
tm_shape(NgaiNdethia.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"), 
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(NgaiNdethia) +
  tm_borders(col = "white", lwd = 2) +
  tm_title("Spatial Distribution of Mean RPI in Ngai Ndethia NR") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Visualising South Kitui NR

SouthKitui.RPI.Mask <- mask(RPI, SouthKitui)
SouthKitui.RPI.Crop <- crop(SouthKitui.RPI.Mask, SouthKitui)

# Averaging across years for visualization
SouthKitui.RPI.Mean <- mean(SouthKitui.RPI.Crop, na.rm = TRUE)

# Visualise
tmap_mode("view")
tm_shape(SouthKitui.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"), 
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(SouthKitui) +
  tm_borders(col = "white", lwd = 2) +
  tm_title("Spatial Distribution of Mean RPI in South Kitui NR") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Visualising AET.Conservancies

AET.Conservancies.RPI.Mask <- mask(RPI, AET.Conservancies)
AET.Conservancies.RPI.Crop <- crop(AET.Conservancies.RPI.Mask, AET.Conservancies)

# Averaging across years for visualization
AET.Conservancies.RPI.Mean <- mean(AET.Conservancies.RPI.Crop, na.rm = TRUE)

# Visualise
tmap_mode("view")
tm_shape(AET.Conservancies.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"), 
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(AET.Conservancies) +
  tm_borders(col = "white", lwd = 2) +
  tm_title("Spatial Distribution of Mean RPI in AET Conservancies") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Visualising AET.Buffers

AET.Buffers.RPI.Mask <- mask(RPI, AET.Buffers)
AET.Buffers.RPI.Crop <- crop(AET.Buffers.RPI.Mask, AET.Buffers)

# Averaging across years for visualization
AET.Buffers.RPI.Mean <- mean(AET.Buffers.RPI.Crop, na.rm = TRUE)

# Visualise
tmap_mode("view")
tm_shape(AET.Buffers.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"), 
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(AET.Buffers) +
  tm_borders(col = "white", lwd = 2) +
  tm_title("Spatial Distribution of Mean RPI in AET Buffers") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Visualising AET.AllZones

AET.AllZones.RPI.Mask <- mask(RPI, AET.AllZones)
AET.AllZones.RPI.Crop <- crop(AET.AllZones.RPI.Mask, AET.AllZones)

# Averaging across years for visualization
AET.AllZones.RPI.Mean <- mean(AET.AllZones.RPI.Crop, na.rm = TRUE)

# Visualise
tmap_mode("view")
tm_shape(AET.AllZones.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"), 
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(AET.Buffers) +
  tm_borders(col = "white", lwd = 2) +
  tm_title("Spatial Distribution of Mean RPI in Amboseli's Surrounding Lands") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Viewing Mean.RPI Maps for Primary Concern Areas

tmap_mode("view")

# Creating individual map panels
Map.Amboseli.RPI.Mean <- tm_shape(Amboseli.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"),
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(Amboseli) + tm_borders(col = "white", lwd = 1.5) +
  tm_title("Amboseli")

Map.TsavoEast.RPI.Mean <- tm_shape(TsavoEast.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"),
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(TsavoEast) + tm_borders(col = "white", lwd = 1.5) +
  tm_title("Tsavo East")

Map.TsavoWest.RPI.Mean <- tm_shape(TsavoWest.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"),
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(TsavoWest) + tm_borders(col = "white", lwd = 1.5) +
  tm_title("Tsavo West")

Map.AET.Conservancies.RPI.Mean <- tm_shape(AET.Conservancies.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"),
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(AET.Conservancies) + tm_borders(col = "white", lwd = 1.5) +
  tm_title("AET Conservancies")

Map.AET.Buffers.RPI.Mean <- tm_shape(AET.Buffers.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"),
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(AET.Buffers) + tm_borders(col = "white", lwd = 1.5) +
  tm_title("AET Buffers")

Map.AET.AllZones.RPI.Mean <- tm_shape(AET.AllZones.RPI.Mean) +
  tm_raster(col.scale = tm_scale_continuous(values = "viridis"),
            col.legend = tm_legend(title = "Mean RPI", reverse = TRUE)) +
  tm_shape(AET.AllZones) + tm_borders(col = "white", lwd = 1.5) +
  tm_title("AET All Zones")

# Combining into grid
tmap_arrange(Map.Amboseli.RPI.Mean, Map.TsavoEast.RPI.Mean,
             Map.TsavoWest.RPI.Mean, Map.AET.Conservancies.RPI.Mean, 
             Map.AET.Buffers.RPI.Mean, Map.AET.AllZones.RPI.Mean, ncol = 3, nrow = 3)
```

```{r}
# Extracting RPI Values for each Area
```

```{r}
## Extracting RPI for Amboseli NP

Amboseli.RPI.Values.Full <- terra::extract(Amboseli.RPI.Crop, Amboseli, cells = TRUE)

### Remove ID column (first column added by extract)
Amboseli.RPI.Values <- Amboseli.RPI.Values.Full[, names(Amboseli.RPI.Crop)]

Amboseli.Summary <- data.frame(
  Layer = names(Amboseli.RPI.Crop),
  Mean = apply(Amboseli.RPI.Values, 2, mean, na.rm = TRUE),
  SD = apply(Amboseli.RPI.Values, 2, sd, na.rm = TRUE),
  Q25 = apply(Amboseli.RPI.Values, 2, quantile, probs = 0.25, na.rm = TRUE),
  Median = apply(Amboseli.RPI.Values, 2, median, na.rm = TRUE),
  Q75 = apply(Amboseli.RPI.Values, 2, quantile, probs = 0.75, na.rm = TRUE)
)

print(Amboseli.Summary)
```

```{r}
## Extracting RPI for TsavoEast NP

TsavoEast.RPI.Values.Full <- terra::extract(TsavoEast.RPI.Crop, TsavoEast, cells= TRUE)

### Remove ID column (first column added by extract)
TsavoEast.RPI.Values <- TsavoEast.RPI.Values.Full[,names(TsavoEast.RPI.Crop)]

TsavoEast.Summary <- data.frame(
  Layer = names(TsavoEast.RPI.Crop),
  Mean = apply(TsavoEast.RPI.Values, 2, mean, na.rm = TRUE),
  SD = apply(TsavoEast.RPI.Values, 2, sd, na.rm = TRUE),
  Q25 = apply(TsavoEast.RPI.Values, 2, quantile, probs = 0.25, na.rm = TRUE),
  Median = apply(TsavoEast.RPI.Values, 2, median, na.rm = TRUE),
  Q75 = apply(TsavoEast.RPI.Values, 2, quantile, probs = 0.75, na.rm = TRUE)
)

print(TsavoEast.Summary)
```

```{r}
## Extracting RPI for TsavoWest NP

TsavoWest.RPI.Values.Full <- terra::extract(TsavoWest.RPI.Crop, TsavoWest, cells= TRUE)

### Remove ID column (first column added by extract)
TsavoWest.RPI.Values <- TsavoWest.RPI.Values.Full[, names(TsavoWest.RPI.Crop)]

TsavoWest.Summary <- data.frame(
  Layer = names(TsavoWest.RPI.Crop),
  Mean = apply(TsavoWest.RPI.Values, 2, mean, na.rm = TRUE),
  SD = apply(TsavoWest.RPI.Values, 2, sd, na.rm = TRUE),
  Q25 = apply(TsavoWest.RPI.Values, 2, quantile, probs = 0.25, na.rm = TRUE),
  Median = apply(TsavoWest.RPI.Values, 2, median, na.rm = TRUE),
  Q75 = apply(TsavoWest.RPI.Values, 2, quantile, probs = 0.75, na.rm = TRUE)
)

print(TsavoWest.Summary)
```

```{r}
## Extracting RPI for ChyuluHills NP

ChyuluHills.RPI.Values.Full <- terra::extract(ChyuluHills.RPI.Crop, ChyuluHills, cells = TRUE)

### Remove ID column (first column added by extract)
ChyuluHills.RPI.Values <- ChyuluHills.RPI.Values.Full[, names(ChyuluHills.RPI.Crop)]

ChyuluHills.Summary <- data.frame(
  Layer = names(ChyuluHills.RPI.Crop),
  Mean = apply(ChyuluHills.RPI.Values, 2, mean, na.rm = TRUE),
  SD = apply(ChyuluHills.RPI.Values, 2, sd, na.rm = TRUE),
  Q25 = apply(ChyuluHills.RPI.Values, 2, quantile, probs = 0.25, na.rm = TRUE),
  Median = apply(ChyuluHills.RPI.Values, 2, median, na.rm = TRUE),
  Q75 = apply(ChyuluHills.RPI.Values, 2, quantile, probs = 0.75, na.rm = TRUE)
)

print(ChyuluHills.Summary)
```

```{r}
## Extracting RPI for NgaiNdethia NR

NgaiNdethia.RPI.Values.Full <- terra::extract(NgaiNdethia.RPI.Crop, NgaiNdethia, cells = TRUE)

### Remove ID column (first column added by extract)
NgaiNdethia.RPI.Values <- NgaiNdethia.RPI.Values.Full[, names(NgaiNdethia.RPI.Crop)]

NgaiNdethia.Summary <- data.frame(
  Layer = names(NgaiNdethia.RPI.Crop),
  Mean = apply(NgaiNdethia.RPI.Values, 2, mean, na.rm = TRUE),
  SD = apply(NgaiNdethia.RPI.Values, 2, sd, na.rm = TRUE),
  Q25 = apply(NgaiNdethia.RPI.Values, 2, quantile, probs = 0.25, na.rm = TRUE),
  Median = apply(NgaiNdethia.RPI.Values, 2, median, na.rm = TRUE),
  Q75 = apply(NgaiNdethia.RPI.Values, 2, quantile, probs = 0.75, na.rm = TRUE)
)

print(NgaiNdethia.Summary)
```

```{r}
## Extracting RPI for SouthKitui NR

SouthKitui.RPI.Values.Full <- terra::extract(SouthKitui.RPI.Crop, SouthKitui, cells= TRUE)

### Remove ID column (first column added by extract)
SouthKitui.RPI.Values <- SouthKitui.RPI.Values.Full[, names(SouthKitui.RPI.Crop)]

SouthKitui.Summary <- data.frame(
  Layer = names(SouthKitui.RPI.Crop),
  Mean = apply(SouthKitui.RPI.Values, 2, mean, na.rm = TRUE),
  SD = apply(SouthKitui.RPI.Values, 2, sd, na.rm = TRUE),
  Q25 = apply(SouthKitui.RPI.Values, 2, quantile, probs = 0.25, na.rm = TRUE),
  Median = apply(SouthKitui.RPI.Values, 2, median, na.rm = TRUE),
  Q75 = apply(SouthKitui.RPI.Values, 2, quantile, probs = 0.75, na.rm = TRUE)
)

print(SouthKitui.Summary)
```

```{r}
## Extracting RPI for AET.Conservancies

AET.Conservancies.RPI.Values.Full <- terra::extract(AET.Conservancies.RPI.Crop, AET.Conservancies, cells= TRUE)

### Remove ID column (first column added by extract)
AET.Conservancies.RPI.Values <- AET.Conservancies.RPI.Values.Full[, names(AET.Conservancies.RPI.Crop)]

AET.Conservancies.Summary <- data.frame(
  Layer = names(AET.Conservancies.RPI.Crop),
  Mean = apply(AET.Conservancies.RPI.Values, 2, mean, na.rm = TRUE),
  SD = apply(AET.Conservancies.RPI.Values, 2, sd, na.rm = TRUE),
  Q25 = apply(AET.Conservancies.RPI.Values, 2, quantile, probs = 0.25, na.rm = TRUE),
  Median = apply(AET.Conservancies.RPI.Values, 2, median, na.rm = TRUE),
  Q75 = apply(AET.Conservancies.RPI.Values, 2, quantile, probs = 0.75, na.rm = TRUE)
)

print(AET.Conservancies.Summary)
```

```{r}
## Extracting RPI for AET.Buffers

AET.Buffers.RPI.Values.Full <- terra::extract(AET.Buffers.RPI.Crop, AET.Buffers, cells = TRUE)

### Remove ID column (first column added by extract)
AET.Buffers.RPI.Values <- AET.Buffers.RPI.Values.Full[, names(AET.Buffers.RPI.Crop)]

AET.Buffers.Summary <- data.frame(
  Layer = names(AET.Buffers.RPI.Crop),
  Mean = apply(AET.Buffers.RPI.Values, 2, mean, na.rm = TRUE),
  SD = apply(AET.Buffers.RPI.Values, 2, sd, na.rm = TRUE),
  Q25 = apply(AET.Buffers.RPI.Values, 2, quantile, probs = 0.25, na.rm = TRUE),
  Median = apply(AET.Buffers.RPI.Values, 2, median, na.rm = TRUE),
  Q75 = apply(AET.Buffers.RPI.Values, 2, quantile, probs = 0.75, na.rm = TRUE)
)

print(AET.Buffers.Summary)
```

```{r}
## Extracting RPI for AET.AllZones

AET.AllZones.RPI.Values.Full <- terra::extract(AET.AllZones.RPI.Crop, AET.AllZones, cells = TRUE)

### Remove ID column (first column added by extract)
AET.AllZones.RPI.Values <- AET.AllZones.RPI.Values.Full[, names(AET.AllZones.RPI.Crop)]

AET.AllZones.Summary <- data.frame(
  Layer = names(AET.AllZones.RPI.Crop),
  Mean = apply(AET.AllZones.RPI.Values, 2, mean, na.rm = TRUE),
  SD = apply(AET.AllZones.RPI.Values, 2, sd, na.rm = TRUE),
  Q25 = apply(AET.AllZones.RPI.Values, 2, quantile, probs = 0.25, na.rm = TRUE),
  Median = apply(AET.AllZones.RPI.Values, 2, median, na.rm = TRUE),
  Q75 = apply(AET.AllZones.RPI.Values, 2, quantile, probs = 0.75, na.rm = TRUE)
)

print(AET.AllZones.Summary)
```

```{r}
# Visualising Extracted RPI Values
```

```{r}
## Visualising Amboseli NP

Amboseli.RPI.Visual <- Amboseli.RPI.Values %>%
  mutate(ID = row_number()) %>%  # optional, to keep track of pixels
  pivot_longer(
    cols = -ID,                 # exclude ID column from pivoting
    names_to = "Layer",
    values_to = "RPI_value"
  ) %>%
  # Keep only layers starting with "rpi."
  filter(grepl("^rpi\\.", Layer)) %>%
  mutate(
    Year = as.integer(sub("rpi\\.", "", Layer)),
    Area = "Amboseli"
  ) %>%
  filter(!is.na(Year) & !is.na(RPI_value)) %>%  # remove NA years or RPI values
  select(ID, Area, Year, RPI_value) ## I will need "ID" for Trend Analysis (Theil-Sen)

# Now plot
ggplot(Amboseli.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_boxplot(fill = "lightblue", outlier.color = "red") +
  labs(
    title = "RPI Distribution Over Years in Amboseli NP",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising Amboseli NP (using a Violin Plot)

ggplot(Amboseli.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.color = "red", alpha = 0.5) +  # optional: overlay boxplot for summary stats
  labs(
    title = "RPI Distribution Over Years in Amboseli NP (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising TsavoEast NP

TsavoEast.RPI.Visual <- TsavoEast.RPI.Values %>%
  mutate(ID = row_number()) %>%  # optional, to keep track of pixels
  pivot_longer(
    cols = -ID,                 # exclude ID column from pivoting
    names_to = "Layer",
    values_to = "RPI_value"
  ) %>%
  # Keeps only layers starting with "rpi."
  filter(grepl("^rpi\\.", Layer)) %>%
  mutate(
    Year = as.integer(sub("rpi\\.", "", Layer)),
    Area = "TsavoEast"
  ) %>%
  filter(!is.na(Year) & !is.na(RPI_value)) %>%  # remove NA years or RPI values
  select(ID, Area, Year, RPI_value)

# Now plot
ggplot(TsavoEast.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_boxplot(fill = "lightblue", outlier.color = "red") +
  labs(
    title = "RPI Distribution Over Years in TsavoEast NP",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising TsavoEast NP (using a Violin Plot)

ggplot(TsavoEast.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.color = "red", alpha = 0.5) +  # optional: overlay boxplot for summary stats
  labs(
    title = "RPI Distribution Over Years in TsavoEast NP (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising TsavoWest NP

TsavoWest.RPI.Visual <- TsavoWest.RPI.Values %>%
  mutate(ID = row_number()) %>%  # optional, to keep track of pixels
  pivot_longer(
    cols = -ID,                 # exclude ID column from pivoting
    names_to = "Layer",
    values_to = "RPI_value"
  ) %>%
  # Keep only layers starting with "rpi."
  filter(grepl("^rpi\\.", Layer)) %>%
  mutate(
    Year = as.integer(sub("rpi\\.", "", Layer)),
    Area = "TsavoWest"
  ) %>%
  filter(!is.na(Year) & !is.na(RPI_value)) %>%  # remove NA years or RPI values
  select(ID, Area, Year, RPI_value)

# Now plot
ggplot(TsavoWest.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_boxplot(fill = "lightblue", outlier.color = "red") +
  labs(
    title = "RPI Distribution Over Years in TsavoWest NP",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising TsavoWest NP (using a Violin Plot)

ggplot(TsavoWest.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.color = "red", alpha = 0.5) +  # optional: overlay boxplot for summary stats
  labs(
    title = "RPI Distribution Over Years in TsavoWest NP (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising ChyuluHills NP

ChyuluHills.RPI.Visual <- ChyuluHills.RPI.Values %>%
  mutate(ID = row_number()) %>%  # optional, to keep track of pixels
  pivot_longer(
    cols = -ID,                 # exclude ID column from pivoting
    names_to = "Layer",
    values_to = "RPI_value"
  ) %>%
  # Keep only layers starting with "rpi."
  filter(grepl("^rpi\\.", Layer)) %>%
  mutate(
    Year = as.integer(sub("rpi\\.", "", Layer)),
    Area = "ChyuluHills"
  ) %>%
  filter(!is.na(Year) & !is.na(RPI_value)) %>%  # remove NA years or RPI values
  select(ID, Area, Year, RPI_value)

# Now plot
ggplot(ChyuluHills.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_boxplot(fill = "lightblue", outlier.color = "red") +
  labs(
    title = "RPI Distribution Over Years in ChyuluHills NP",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising ChyuluHills NP (using a Violin Plot)

ggplot(ChyuluHills.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.color = "red", alpha = 0.5) +  # optional: overlay boxplot for summary stats
  labs(
    title = "RPI Distribution Over Years in ChyuluHills NP (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising NgaiNdethia NR

NgaiNdethia.RPI.Visual <- NgaiNdethia.RPI.Values %>%
  mutate(ID = row_number()) %>%  # optional, to keep track of pixels
  pivot_longer(
    cols = -ID,                 # exclude ID column from pivoting
    names_to = "Layer",
    values_to = "RPI_value"
  ) %>%
  # Keep only layers starting with "rpi."
  filter(grepl("^rpi\\.", Layer)) %>%
  mutate(
    Year = as.integer(sub("rpi\\.", "", Layer)),
    Area = "NgaiNdethia"
  ) %>%
  filter(!is.na(Year) & !is.na(RPI_value)) %>%  # remove NA years or RPI values
  select(ID, Area, Year, RPI_value)

# Now plot
ggplot(NgaiNdethia.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_boxplot(fill = "lightblue", outlier.color = "red") +
  labs(
    title = "RPI Distribution Over Years in NgaiNdethia NR",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising NgaiNdethia NR (using a Violin Plot)

ggplot(NgaiNdethia.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.color = "red", alpha = 0.5) +  # optional: overlay boxplot for summary stats
  labs(
    title = "RPI Distribution Over Years in NgaiNdethia NR (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising SouthKitui NR

SouthKitui.RPI.Visual <- SouthKitui.RPI.Values %>%
  mutate(ID = row_number()) %>%  # optional, to keep track of pixels
  pivot_longer(
    cols = -ID,                 # exclude ID column from pivoting
    names_to = "Layer",
    values_to = "RPI_value"
  ) %>%
  # Keep only layers starting with "rpi."
  filter(grepl("^rpi\\.", Layer)) %>%
  mutate(
    Year = as.integer(sub("rpi\\.", "", Layer)),
    Area = "SouthKitui"
  ) %>%
  filter(!is.na(Year) & !is.na(RPI_value)) %>%  # remove NA years or RPI values
  select(ID, Area, Year, RPI_value)

# Now plot
ggplot(SouthKitui.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_boxplot(fill = "lightblue", outlier.color = "red") +
  labs(
    title = "RPI Distribution Over Years in SouthKitui NR",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising SouthKitui NR (using a Violin Plot)

ggplot(SouthKitui.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.color = "red", alpha = 0.5) +  # optional: overlay boxplot for summary stats
  labs(
    title = "RPI Distribution Over Years in SouthKitui NR (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising AET.Conservancies

AET.Conservancies.RPI.Visual <- AET.Conservancies.RPI.Values %>%
  mutate(ID = row_number()) %>%  # optional, to keep track of pixels
  pivot_longer(
    cols = -ID,                 # exclude ID column from pivoting
    names_to = "Layer",
    values_to = "RPI_value"
  ) %>%
  # Keep only layers starting with "rpi."
  filter(grepl("^rpi\\.", Layer)) %>%
  mutate(
    Year = as.integer(sub("rpi\\.", "", Layer)),
    Area = "AET.Conservancies"
  ) %>%
  filter(!is.na(Year) & !is.na(RPI_value)) %>%  # remove NA years or RPI values
  select(ID, Area, Year, RPI_value)

# Now plot
ggplot(AET.Conservancies.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_boxplot(fill = "lightblue", outlier.color = "red") +
  labs(
    title = "RPI Distribution Over Years in AET.Conservancies",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising AET.Conservancies (using a Violin Plot)

ggplot(AET.Conservancies.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.color = "red", alpha = 0.5) +  # optional: overlay boxplot for summary stats
  labs(
    title = "RPI Distribution Over Years in AET.Conservancies (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising AET.Buffers

AET.Buffers.RPI.Visual <- AET.Buffers.RPI.Values %>%
  mutate(ID = row_number()) %>%  # optional, to keep track of pixels
  pivot_longer(
    cols = -ID,                 # exclude ID column from pivoting
    names_to = "Layer",
    values_to = "RPI_value"
  ) %>%
  # Keep only layers starting with "rpi."
  filter(grepl("^rpi\\.", Layer)) %>%
  mutate(
    Year = as.integer(sub("rpi\\.", "", Layer)),
    Area = "AET.Buffers"
  ) %>%
  filter(!is.na(Year) & !is.na(RPI_value)) %>%  # remove NA years or RPI values
  select(ID, Area, Year, RPI_value)

# Now plot
ggplot(AET.Buffers.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_boxplot(fill = "lightblue", outlier.color = "red") +
  labs(
    title = "RPI Distribution Over Years in AET.Buffers",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising AET.Buffers (using a Violin Plot)

ggplot(AET.Buffers.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.color = "red", alpha = 0.5) +  # optional: overlay boxplot for summary stats
  labs(
    title = "RPI Distribution Over Years in AET.Buffers (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising AET.AllZones

AET.AllZones.RPI.Visual <- AET.AllZones.RPI.Values %>%
  mutate(ID = row_number()) %>%  # optional, to keep track of pixels
  pivot_longer(
    cols = -ID,                 # exclude ID column from pivoting
    names_to = "Layer",
    values_to = "RPI_value"
  ) %>%
  # Keep only layers starting with "rpi."
  filter(grepl("^rpi\\.", Layer)) %>%
  mutate(
    Year = as.integer(sub("rpi\\.", "", Layer)),
    Area = "AET.AllZones"
  ) %>%
  filter(!is.na(Year) & !is.na(RPI_value)) %>%  # remove NA years or RPI values
  select(ID, Area, Year, RPI_value) ## I will need "ID" for Trend Analysis (Theil-Sen)

# Now plot
ggplot(AET.AllZones.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_boxplot(fill = "lightblue", outlier.color = "red") +
  labs(
    title = "RPI Distribution Over Years in AET.AllZones",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Conversation on refining the Violin plots:

# 1.Skepticism about RPI Fluctuations:
  # Do not fully trust year-to-year fluctuations in the (RPI).

#2.Focus on Comparisons:
  # Emphasise comparisons in:
    # (i) Average performance
    # (ii) Trends over time
  # Analyse these comparisons across different spatial units and/or management periods.

# 3. Signal vs. Noise:
  # Aim to focus on the real signal rather than the noise in the data.

# 4. Outlier Classification:
  # Recommend including arguments against disabling "outlier" classification.
  # Suggest that there are insufficient grounds to treat the red dots differently.
```

```{r}
## Visualising Amboseli NP

ggplot(Amboseli.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.4) +  # removes red outlier dots
  stat_summary(fun = mean, geom = "line", aes(group = 1), color = "darkblue", linewidth = 0.6) + #Added mean line to get the general pattern
  stat_summary(fun = mean, geom = "point", shape = 21, fill = "purple", size = 2) + # Combined the mean line with points to make it easier to visualise
  labs(
    title = "RPI Distribution Over Years in Amboseli NP (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising Mean RPI over Amboseli NP as a line 

Amboseli.Mean <- Amboseli.RPI.Visual %>%
  group_by(Year) %>%
  summarise(Mean_RPI = mean(RPI_value, na.rm = TRUE))

ggplot(Amboseli.Mean, aes(x = Year, y = Mean_RPI)) +
  geom_line(color = "darkgreen", linewidth = 0.8) +
  geom_point(color = "black", fill = "purple", shape = 21, size = 2) +
  labs(
    title = "Mean RPI Over Time in Amboseli NP",
    x = "Year",
    y = "Mean RPI"
  ) +
  theme_beautiful()
```

```{r}
## Visualising TsavoEast NP

ggplot(TsavoEast.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.4) +  # removes red outlier dots
  stat_summary(fun = mean, geom = "line", aes(group = 1), color = "darkblue", linewidth = 0.6) + #Added mean line to get the general pattern
  stat_summary(fun = mean, geom = "point", shape = 21, fill = "purple", size = 2) + # Combined the mean line with points to make it easier to visualise
  labs(
    title = "RPI Distribution Over Years in Tsavo East NP (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising Mean RPI over TsavoEast NP as a line 

TsavoEast.Mean <- TsavoEast.RPI.Visual %>%
  group_by(Year) %>%
  summarise(Mean_RPI = mean(RPI_value, na.rm = TRUE))

ggplot(TsavoEast.Mean, aes(x = Year, y = Mean_RPI)) +
  geom_line(color = "darkgreen", linewidth = 0.8) +
  geom_point(color = "black", fill = "purple", shape = 21, size = 2) +
  labs(
    title = "Mean RPI Over Time in Tsavo East NP",
    x = "Year",
    y = "Mean RPI"
  ) +
  theme_beautiful()
```

```{r}
## Visualising TsavoWest NP

ggplot(TsavoWest.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.4) +  # removes red outlier dots
  stat_summary(fun = mean, geom = "line", aes(group = 1), color = "darkblue", linewidth = 0.6) + #Added mean line to get the general pattern
  stat_summary(fun = mean, geom = "point", shape = 21, fill = "purple", size = 2) + # Combined the mean line with points to make it easier to visualise
  labs(
    title = "RPI Distribution Over Years in Tsavo West NP (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising Mean RPI over TsavoWest NP as a line 

TsavoWest.Mean <- TsavoWest.RPI.Visual %>%
  group_by(Year) %>%
  summarise(Mean_RPI = mean(RPI_value, na.rm = TRUE))

ggplot(TsavoWest.Mean, aes(x = Year, y = Mean_RPI)) +
  geom_line(color = "darkgreen", linewidth = 0.8) +
  geom_point(color = "black", fill = "purple", shape = 21, size = 2) +
  labs(
    title = "Mean RPI Over Time in Tsavo West NP",
    x = "Year",
    y = "Mean RPI"
  ) +
  theme_beautiful()
```

```{r}
## Visualising ChyuluHills NP

ggplot(ChyuluHills.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.4) +  # removes red outlier dots
  stat_summary(fun = mean, geom = "line", aes(group = 1), color = "darkblue", linewidth = 0.6) + #Added mean line to get the general pattern
  stat_summary(fun = mean, geom = "point", shape = 21, fill = "purple", size = 2) + # Combined the mean line with points to make it easier to visualise
  labs(
    title = "RPI Distribution Over Years in Chyulu Hills NP (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising Mean RPI over ChyuluHills NP as a line 

ChyuluHills.Mean <- ChyuluHills.RPI.Visual %>%
  group_by(Year) %>%
  summarise(Mean_RPI = mean(RPI_value, na.rm = TRUE))

ggplot(ChyuluHills.Mean, aes(x = Year, y = Mean_RPI)) +
  geom_line(color = "darkgreen", linewidth = 0.8) +
  geom_point(color = "black", fill = "purple", shape = 21, size = 2) +
  labs(
    title = "Mean RPI Over Time in Chyulu Hills NP",
    x = "Year",
    y = "Mean RPI"
  ) +
  theme_beautiful()
```

```{r}
## Visualising NgaiNdethia NR

ggplot(NgaiNdethia.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.4) +  # removes red outlier dots
  stat_summary(fun = mean, geom = "line", aes(group = 1), color = "darkblue", linewidth = 0.6) + #Added mean line to get the general pattern
  stat_summary(fun = mean, geom = "point", shape = 21, fill = "purple", size = 2) + # Combined the mean line with points to make it easier to visualise
  labs(
    title = "RPI Distribution Over Years in Ngai Ndethia NR (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising Mean RPI over NgaiNdethia NR as a line 

NgaiNdethia.Mean <- NgaiNdethia.RPI.Visual %>%
  group_by(Year) %>%
  summarise(Mean_RPI = mean(RPI_value, na.rm = TRUE))

ggplot(NgaiNdethia.Mean, aes(x = Year, y = Mean_RPI)) +
  geom_line(color = "darkgreen", linewidth = 0.8) +
  geom_point(color = "black", fill = "purple", shape = 21, size = 2) +
  labs(
    title = "Mean RPI Over Time in Ngai Ndethia NR",
    x = "Year",
    y = "Mean RPI"
  ) +
  theme_beautiful()
```

```{r}
## Visualising SouthKitui NR

ggplot(SouthKitui.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.4) +  # removes red outlier dots
  stat_summary(fun = mean, geom = "line", aes(group = 1), color = "darkblue", linewidth = 0.6) + #Added mean line to get the general pattern
  stat_summary(fun = mean, geom = "point", shape = 21, fill = "purple", size = 2) + # Combined the mean line with points to make it easier to visualise
  labs(
    title = "RPI Distribution Over Years in South Kitui NR (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising Mean RPI over SouthKitui NR as a line 

SouthKitui.Mean <- SouthKitui.RPI.Visual %>%
  group_by(Year) %>%
  summarise(Mean_RPI = mean(RPI_value, na.rm = TRUE))

ggplot(SouthKitui.Mean, aes(x = Year, y = Mean_RPI)) +
  geom_line(color = "darkgreen", linewidth = 0.8) +
  geom_point(color = "black", fill = "purple", shape = 21, size = 2) +
  labs(
    title = "Mean RPI Over Time in South Kitui NR",
    x = "Year",
    y = "Mean RPI"
  ) +
  theme_beautiful()
```

```{r}
## Visualising AET.Conservancies

ggplot(AET.Conservancies.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.4) +  # removes red outlier dots
  stat_summary(fun = mean, geom = "line", aes(group = 1), color = "darkblue", linewidth = 0.6) + #Added mean line to get the general pattern
  stat_summary(fun = mean, geom = "point", shape = 21, fill = "purple", size = 2) + # Combined the mean line with points to make it easier to visualise
  labs(
    title = "RPI Distribution Over Years in AET.Conservancies (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising Mean RPI over AET.Conservancies as a line 

AET.Conservancies.Mean <- AET.Conservancies.RPI.Visual %>%
  group_by(Year) %>%
  summarise(Mean_RPI = mean(RPI_value, na.rm = TRUE))

ggplot(AET.Conservancies.Mean, aes(x = Year, y = Mean_RPI)) +
  geom_line(color = "darkgreen", linewidth = 0.8) +
  geom_point(color = "black", fill = "purple", shape = 21, size = 2) +
  labs(
    title = "Mean RPI Over Time in AET.Conservancies",
    x = "Year",
    y = "Mean RPI"
  ) +
  theme_beautiful()
```

```{r}
## Visualising AET.Buffers

## Visualising Amboseli NP

ggplot(AET.Buffers.RPI.Visual, aes(x = factor(Year), y = RPI_value)) +
  geom_violin(fill = "lightblue", color = "black", alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.4) +  # removes red outlier dots
  stat_summary(fun = mean, geom = "line", aes(group = 1), color = "darkblue", linewidth = 0.6) + #Added mean line to get the general pattern
  stat_summary(fun = mean, geom = "point", shape = 21, fill = "purple", size = 2) + # Combined the mean line with points to make it easier to visualise
  labs(
    title = "RPI Distribution Over Years in AET.Buffers (Violin Plot)",
    x = "Year",
    y = "RPI Value"
  ) +
  theme_beautiful()
```

```{r}
## Visualising Mean RPI over AET.Buffers as a line 

AET.Buffers.Mean <- AET.Buffers.RPI.Visual %>%
  group_by(Year) %>%
  summarise(Mean_RPI = mean(RPI_value, na.rm = TRUE))

ggplot(AET.Buffers.Mean, aes(x = Year, y = Mean_RPI)) +
  geom_line(color = "darkgreen", linewidth = 0.8) +
  geom_point(color = "black", fill = "purple", shape = 21, size = 2) +
  labs(
    title = "Mean RPI Over Time in AET.Buffers",
    x = "Year",
    y = "Mean RPI"
  ) +
  theme_beautiful()
```

```{r}
# Estimating Theil-Sen Slope Trends
```

```{r}
## Theil-Sen across Amboseli NP

  # Sorting data by "Year" & "ID"
Amboseli.RPI.Visual.Arranged <- Amboseli.RPI.Visual %>% arrange(ID, Year)

# Split data by pixel ID
Amboseli.Pixel.List <- Amboseli.RPI.Visual.Arranged %>% group_split(ID)

# Apply sens.slope to each pixel group
Amboseli.TheilSen <- map_dfr(Amboseli.Pixel.List, function(df) {
  if (sum(!is.na(df$RPI_value)) >= 3) {
    slope <- tryCatch(
      sens.slope(df$RPI_value)$estimates,
      error = function(e) NA_real_
    )
  } else {
    slope <- NA_real_
  }
  tibble(ID = unique(df$ID), Slope = slope)
})

  # Joining slope results back with area info
Amboseli.TheilSen <- Amboseli.TheilSen %>%
  mutate(Area = "Amboseli")

  # Getting overall summary per area
Amboseli.SummaryTrend <- Amboseli.TheilSen %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope))
  )
```

```{r}
## Theil-Sen across TsavoEast NP

  # Sorting data by "Year" & "ID"
TsavoEast.RPI.Visual.Arranged <- TsavoEast.RPI.Visual %>% arrange(ID, Year)

# Split data by pixel ID
TsavoEast.Pixel.List <- TsavoEast.RPI.Visual.Arranged %>% group_split(ID)

# Apply sens.slope to each pixel group
TsavoEast.TheilSen <- map_dfr(TsavoEast.Pixel.List, function(df) {
  if (sum(!is.na(df$RPI_value)) >= 3) {
    slope <- tryCatch(
      sens.slope(df$RPI_value)$estimates,
      error = function(e) NA_real_
    )
  } else {
    slope <- NA_real_
  }
  tibble(ID = unique(df$ID), Slope = slope)
})

  # Joining slope results back with area info
TsavoEast.TheilSen <- TsavoEast.TheilSen %>%
  mutate(Area = "TsavoEast")

  # Getting overall summary per area
TsavoEast.SummaryTrend <- TsavoEast.TheilSen %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope))
  )
```

```{r}
## Theil-Sen across TsavoWest NP

  # Sorting data by "Year" & "ID"
TsavoWest.RPI.Visual.Arranged <- TsavoWest.RPI.Visual %>% arrange(ID, Year)

# Split data by pixel ID
TsavoWest.Pixel.List <- TsavoWest.RPI.Visual.Arranged %>% group_split(ID)

# Apply sens.slope to each pixel group
TsavoWest.TheilSen <- map_dfr(TsavoWest.Pixel.List, function(df) {
  if (sum(!is.na(df$RPI_value)) >= 3) {
    slope <- tryCatch(
      sens.slope(df$RPI_value)$estimates,
      error = function(e) NA_real_
    )
  } else {
    slope <- NA_real_
  }
  tibble(ID = unique(df$ID), Slope = slope)
})

  # Joining slope results back with area info
TsavoWest.TheilSen <- TsavoWest.TheilSen %>%
  mutate(Area = "TsavoWest")

  # Getting overall summary per area
TsavoWest.SummaryTrend <- TsavoWest.TheilSen %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope))
  )
```

```{r}
## Theil-Sen across ChyuluHills NP

  # Sorting data by "Year" & "ID"
ChyuluHills.RPI.Visual.Arranged <- ChyuluHills.RPI.Visual %>% arrange(ID, Year)

# Split data by pixel ID 
    #{"group_split()" - apply a time-series analysis function independently to the time serieS associated with each distinct spatial unit/pixel}
ChyuluHills.Pixel.List <- ChyuluHills.RPI.Visual.Arranged %>% group_split(ID)

# Apply sens.slope to each pixel group
ChyuluHills.TheilSen <- map_dfr(ChyuluHills.Pixel.List, function(df) {
  if (sum(!is.na(df$RPI_value)) >= 3) {
    slope <- tryCatch(
      sens.slope(df$RPI_value)$estimates,
      error = function(e) NA_real_
    )
  } else {
    slope <- NA_real_
  }
  tibble(ID = unique(df$ID), Slope = slope)
})

  # Joining slope results back with area info
ChyuluHills.TheilSen <- ChyuluHills.TheilSen %>%
  mutate(Area = "ChyuluHills")

  # Getting overall summary per area
ChyuluHills.SummaryTrend <- ChyuluHills.TheilSen %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope))
  )
```

```{r}
## Theil-Sen across NgaiNdethia NR

  # Sorting data by "Year" & "ID"
NgaiNdethia.RPI.Visual.Arranged <- NgaiNdethia.RPI.Visual %>% arrange(ID, Year)

# Split data by pixel ID
NgaiNdethia.Pixel.List <- NgaiNdethia.RPI.Visual.Arranged %>% group_split(ID)

# Apply sens.slope to each pixel group
NgaiNdethia.TheilSen <- map_dfr(NgaiNdethia.Pixel.List, function(df) {
  if (sum(!is.na(df$RPI_value)) >= 3) {
    slope <- tryCatch(
      sens.slope(df$RPI_value)$estimates,
      error = function(e) NA_real_
    )
  } else {
    slope <- NA_real_
  }
  tibble(ID = unique(df$ID), Slope = slope)
})

  # Joining slope results back with area info
NgaiNdethia.TheilSen <- NgaiNdethia.TheilSen %>%
  mutate(Area = "NgaiNdethia")

  # Getting overall summary per area
NgaiNdethia.SummaryTrend <- NgaiNdethia.TheilSen %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope))
  )
```

```{r}
## Theil-Sen across SouthKitui NR

  # Sorting data by "Year" & "ID"
SouthKitui.RPI.Visual.Arranged <- SouthKitui.RPI.Visual %>% arrange(ID, Year)

# Split data by pixel ID
SouthKitui.Pixel.List <- SouthKitui.RPI.Visual.Arranged %>% group_split(ID)

# Apply sens.slope to each pixel group
SouthKitui.TheilSen <- map_dfr(SouthKitui.Pixel.List, function(df) {
  if (sum(!is.na(df$RPI_value)) >= 3) {
    slope <- tryCatch(
      sens.slope(df$RPI_value)$estimates,
      error = function(e) NA_real_
    )
  } else {
    slope <- NA_real_
  }
  tibble(ID = unique(df$ID), Slope = slope)
})

  # Joining slope results back with area info
SouthKitui.TheilSen <- SouthKitui.TheilSen %>%
  mutate(Area = "SouthKitui")

  # Getting overall summary per area
SouthKitui.SummaryTrend <- SouthKitui.TheilSen %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope))
  )
```

```{r}
## Theil-Sen across AET.Conservancies

  # Sorting data by "Year" & "ID"
AET.Conservancies.RPI.Visual.Arranged <- AET.Conservancies.RPI.Visual %>% arrange(ID, Year)

# Split data by pixel ID
AET.Conservancies.Pixel.List <- AET.Conservancies.RPI.Visual.Arranged %>% group_split(ID)

# Apply sens.slope to each pixel group
AET.Conservancies.TheilSen <- map_dfr(AET.Conservancies.Pixel.List, function(df) {
  if (sum(!is.na(df$RPI_value)) >= 3) {
    slope <- tryCatch(
      sens.slope(df$RPI_value)$estimates,
      error = function(e) NA_real_
    )
  } else {
    slope <- NA_real_
  }
  tibble(ID = unique(df$ID), Slope = slope)
})

  # Joining slope results back with area info
AET.Conservancies.TheilSen <- AET.Conservancies.TheilSen %>%
  mutate(Area = "Amboseli")

  # Getting overall summary per area
AET.Conservancies.SummaryTrend <- AET.Conservancies.TheilSen %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope))
  )
```

```{r}
## Theil-Sen across AET.Buffers

  # Sorting data by "Year" & "ID"
AET.Buffers.RPI.Visual.Arranged <- AET.Buffers.RPI.Visual %>% arrange(ID, Year)

# Split data by pixel ID
AET.Buffers.Pixel.List <- AET.Buffers.RPI.Visual.Arranged %>% group_split(ID)

# Apply sens.slope to each pixel group
AET.Buffers.TheilSen <- map_dfr(AET.Buffers.Pixel.List, function(df) {
  if (sum(!is.na(df$RPI_value)) >= 3) {
    slope <- tryCatch(
      sens.slope(df$RPI_value)$estimates,
      error = function(e) NA_real_
    )
  } else {
    slope <- NA_real_
  }
  tibble(ID = unique(df$ID), Slope = slope)
})

  # Joining slope results back with area info
AET.Buffers.TheilSen <- AET.Buffers.TheilSen %>%
  mutate(Area = "AET.Buffers")

  # Getting overall summary per area
AET.Buffers.SummaryTrend <- AET.Buffers.TheilSen %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope))
  )
```

```{r}
## Theil-Sen across AET.AllZones

  # Sorting data by "Year" & "ID"
AET.AllZones.RPI.Visual.Arranged <- AET.AllZones.RPI.Visual %>% arrange(ID, Year)

# Split data by pixel ID
AET.AllZones.Pixel.List <- AET.AllZones.RPI.Visual.Arranged %>% group_split(ID)

# Apply sens.slope to each pixel group
AET.AllZones.TheilSen <- map_dfr(AET.AllZones.Pixel.List, function(df) {
  if (sum(!is.na(df$RPI_value)) >= 3) {
    slope <- tryCatch(
      sens.slope(df$RPI_value)$estimates,
      error = function(e) NA_real_
    )
  } else {
    slope <- NA_real_
  }
  tibble(ID = unique(df$ID), Slope = slope)
})

  # Joining slope results back with area info
AET.AllZones.TheilSen <- AET.AllZones.TheilSen %>%
  mutate(Area = "AET.AllZones")

  # Getting overall summary per area
AET.AllZones.SummaryTrend <- AET.AllZones.TheilSen %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope))
  )
```

```{r}
# Visualising MeanSlope across study area

All.Pixel.Slopes <- bind_rows(
  Amboseli.TheilSen, TsavoEast.TheilSen, TsavoWest.TheilSen, ChyuluHills.TheilSen,
  NgaiNdethia.TheilSen, SouthKitui.TheilSen, AET.Conservancies.TheilSen, AET.Buffers.TheilSen)


All.Trends.Summary <- All.Pixel.Slopes %>%
  group_by(Area) %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope)),
    .groups = "drop"
  )
    ## All.Trends.Summary summarises the overall direction and strength of change in RPI for each area over the full time series.


ggplot(All.Trends.Summary, aes(x = reorder(Area, MeanSlope), y = MeanSlope)) +
  geom_col(fill = "steelblue", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "darkred") +
  labs(
    title = "Mean RPI Trend (TheilSen) by Area",
    x = "Area",
    y = "Mean Slope"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
## Visualising Violin Plot to compare across the study area

ggplot(All.Pixel.Slopes, aes(x = Area, y = Slope, fill = Area)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  labs(title = "Distribution of RPI Trends (TheilSen Slopes) by Area", x = "Area", y = "Slope") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# Creating Raster Maps of Theil-Sen Slopes
```

```{r}
## Amboseli Raster Map of Theil-Sen Slopes

# 1. I shall use the original raster as a template using only 1 layer for structure
Amboseli.Slope.Raster <- terra::rast(Amboseli.RPI.Crop[[1]])
terra::values(Amboseli.Slope.Raster) <- NA  # blank it out

# 2. I shall then link slope values to cell numbers
Amboseli.Cell.Map <- data.frame(ID = 1:nrow(Amboseli.RPI.Values.Full), cell = Amboseli.RPI.Values.Full$cell)

  # Merging slopes with cells
Amboseli.Slope.Cells <- dplyr::left_join(Amboseli.TheilSen, Amboseli.Cell.Map, by = "ID")

# 3. Populate slope values into raster cells
Amboseli.Slope.Raster[Amboseli.Slope.Cells$cell] <- Amboseli.Slope.Cells$Slope

# 4. Plot the raster
tm_shape(Amboseli.Slope.Raster) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
    col.legend = tm_legend(title = "TheilSen Slope", reverse = TRUE)) +
  tm_title("Spatial Distribution of RPI Trends  Amboseli") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## TsavoEast Raster Map of Theil-Sen Slopes

# 1. I shall use the original raster as a template using only 1 layer for structure
TsavoEast.Slope.Raster <- terra::rast(TsavoEast.RPI.Crop[[1]])
terra::values(TsavoEast.Slope.Raster) <- NA  # blank it out

# 2. I shall then link slope values to cell numbers
TsavoEast.Cell.Map <- data.frame(ID = 1:nrow(TsavoEast.RPI.Values.Full), cell = TsavoEast.RPI.Values.Full$cell)

  # Merging slopes with cells
TsavoEast.Slope.Cells <- dplyr::left_join(TsavoEast.TheilSen, TsavoEast.Cell.Map, by = "ID")

# 3. Populate slope values into raster cells
TsavoEast.Slope.Raster[TsavoEast.Slope.Cells$cell] <- TsavoEast.Slope.Cells$Slope

# 4. Plot the raster
tm_shape(TsavoEast.Slope.Raster) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
    col.legend = tm_legend(title = "TheilSen Slope", reverse= TRUE)) +
  tm_title("Spatial Distribution of RPI Trends  Tsavo East") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## TsavoWest Raster Map of Theil-Sen Slopes

# 1. I shall use the original raster as a template using only 1 layer for structure
TsavoWest.Slope.Raster <- terra::rast(TsavoWest.RPI.Crop[[1]])
terra::values(TsavoWest.Slope.Raster) <- NA  # blank it out

# 2. I shall then link slope values to cell numbers
TsavoWest.Cell.Map <- data.frame(ID = 1:nrow(TsavoWest.RPI.Values.Full), cell = TsavoWest.RPI.Values.Full$cell)

  # Merging slopes with cells
TsavoWest.Slope.Cells <- dplyr::left_join(TsavoWest.TheilSen, TsavoWest.Cell.Map, by = "ID")

# 3. Populate slope values into raster cells
TsavoWest.Slope.Raster[TsavoWest.Slope.Cells$cell] <- TsavoWest.Slope.Cells$Slope

# 4. Plot the raster
tm_shape(TsavoWest.Slope.Raster) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
    col.legend = tm_legend(title = "TheilSen Slope", reverse = TRUE)) +
  tm_title("Spatial Distribution of RPI Trends  Tsavo West") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## ChyuluHills Raster Map of Theil-Sen Slopes

# 1. I shall use the original raster as a template using only 1 layer for structure
ChyuluHills.Slope.Raster <- terra::rast(ChyuluHills.RPI.Crop[[1]])
terra::values(ChyuluHills.Slope.Raster) <- NA  # blank it out

# 2. I shall then link slope values to cell numbers
ChyuluHills.Cell.Map <- data.frame(ID = 1:nrow(ChyuluHills.RPI.Values.Full), cell = ChyuluHills.RPI.Values.Full$cell)

  # Merging slopes with cells
ChyuluHills.Slope.Cells <- dplyr::left_join(ChyuluHills.TheilSen, ChyuluHills.Cell.Map, by = "ID")

# 3. Populate slope values into raster cells
ChyuluHills.Slope.Raster[ChyuluHills.Slope.Cells$cell] <- ChyuluHills.Slope.Cells$Slope

# 4. Plot the raster
tm_shape(ChyuluHills.Slope.Raster) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
    col.legend = tm_legend(title = "TheilSen Slope", reverse = TRUE)) +
  tm_title("Spatial Distribution of RPI Trends  Chyulu Hills") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## NgaiNdethia Raster Map of Theil-Sen Slopes

# 1. I shall use the original raster as a template using only 1 layer for structure
NgaiNdethia.Slope.Raster <- terra::rast(NgaiNdethia.RPI.Crop[[1]])
terra::values(NgaiNdethia.Slope.Raster) <- NA  # blank it out

# 2. I shall then link slope values to cell numbers
NgaiNdethia.Cell.Map <- data.frame(ID = 1:nrow(NgaiNdethia.RPI.Values.Full), cell = NgaiNdethia.RPI.Values.Full$cell)

  # Merging slopes with cells
NgaiNdethia.Slope.Cells <- dplyr::left_join(NgaiNdethia.TheilSen, NgaiNdethia.Cell.Map, by = "ID")

# 3. Populate slope values into raster cells
NgaiNdethia.Slope.Raster[NgaiNdethia.Slope.Cells$cell] <- NgaiNdethia.Slope.Cells$Slope

# 4. Plot the raster
tm_shape(NgaiNdethia.Slope.Raster) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
    col.legend = tm_legend(title = "TheilSen Slope", reverse = TRUE)) +
  tm_title("Spatial Distribution of RPI Trends  Ngai Ndethia") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## SouthKitui Raster Map of Theil-Sen Slopes

# 1. I shall use the original raster as a template using only 1 layer for structure
SouthKitui.Slope.Raster <- terra::rast(SouthKitui.RPI.Crop[[1]])
terra::values(SouthKitui.Slope.Raster) <- NA  # blank it out

# 2. I shall then link slope values to cell numbers
SouthKitui.Cell.Map <- data.frame(ID = 1:nrow(SouthKitui.RPI.Values.Full), cell = SouthKitui.RPI.Values.Full$cell)

  # Merging slopes with cells
SouthKitui.Slope.Cells <- dplyr::left_join(SouthKitui.TheilSen, SouthKitui.Cell.Map, by = "ID")

# 3. Populate slope values into raster cells
SouthKitui.Slope.Raster[SouthKitui.Slope.Cells$cell] <- SouthKitui.Slope.Cells$Slope

# 4. Plot the raster
tm_shape(SouthKitui.Slope.Raster) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
    col.legend = tm_legend(title = "TheilSen Slope", reverse = TRUE)) +
  tm_title("Spatial Distribution of RPI Trends  South Kitui") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## AET.Conservancies Raster Map of Theil-Sen Slopes

# 1. I shall use the original raster as a template using only 1 layer for structure
AET.Conservancies.Slope.Raster <- terra::rast(AET.Conservancies.RPI.Crop[[1]])
terra::values(AET.Conservancies.Slope.Raster) <- NA  # blank it out

# 2. I shall then link slope values to cell numbers
AET.Conservancies.Cell.Map <- data.frame(ID = 1:nrow(AET.Conservancies.RPI.Values.Full), cell = AET.Conservancies.RPI.Values.Full$cell)

  # Merging slopes with cells
AET.Conservancies.Slope.Cells <- dplyr::left_join(AET.Conservancies.TheilSen, AET.Conservancies.Cell.Map, by = "ID")

# 3. Populate slope values into raster cells
AET.Conservancies.Slope.Raster[AET.Conservancies.Slope.Cells$cell] <- AET.Conservancies.Slope.Cells$Slope

# 4. Plot the raster
tm_shape(AET.Conservancies.Slope.Raster) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
    col.legend = tm_legend(title = "TheilSen Slope", reverse = TRUE)) +
  tm_title("Spatial Distribution of RPI Trends  AET Conservancies") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## AET.Buffers Raster Map of Theil-Sen Slopes

# 1. I shall use the original raster as a template using only 1 layer for structure
AET.Buffers.Slope.Raster <- terra::rast(AET.Buffers.RPI.Crop[[1]])
terra::values(AET.Buffers.Slope.Raster) <- NA  # blank it out

# 2. I shall then link slope values to cell numbers
AET.Buffers.Cell.Map <- data.frame(ID = 1:nrow(AET.Buffers.RPI.Values.Full), cell = AET.Buffers.RPI.Values.Full$cell)

  # Merging slopes with cells
AET.Buffers.Slope.Cells <- dplyr::left_join(AET.Buffers.TheilSen, AET.Buffers.Cell.Map, by = "ID")

# 3. Populate slope values into raster cells
AET.Buffers.Slope.Raster[AET.Buffers.Slope.Cells$cell] <- AET.Buffers.Slope.Cells$Slope

# 4. Plot the raster
tm_shape(AET.Buffers.Slope.Raster) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
    col.legend = tm_legend(title = "TheilSen Slope", reverse= TRUE)) +
  tm_title("Spatial Distribution of RPI Trends  AET Buffers") +
  tm_layout(legend.outside = TRUE)
```

```{r}
## AET.AllZones Raster Map of Theil-Sen Slopes

# 1. I shall use the original raster as a template using only 1 layer for structure
AET.AllZones.Slope.Raster <- terra::rast(AET.AllZones.RPI.Crop[[1]])
terra::values(AET.AllZones.Slope.Raster) <- NA  # blank it out

# 2. I shall then link slope values to cell numbers
AET.AllZones.Cell.Map <- data.frame(ID = 1:nrow(AET.AllZones.RPI.Values.Full), cell = AET.AllZones.RPI.Values.Full$cell)

  # Merging slopes with cells
AET.AllZones.Slope.Cells <- dplyr::left_join(AET.AllZones.TheilSen, AET.AllZones.Cell.Map, by = "ID")

# 3. Populate slope values into raster cells
AET.AllZones.Slope.Raster[AET.AllZones.Slope.Cells$cell] <- AET.AllZones.Slope.Cells$Slope

# 4. Plot the raster
tm_shape(AET.AllZones.Slope.Raster) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
    col.legend = tm_legend(title = "TheilSen Slope", reverse= TRUE)) +
  tm_title("Spatial Distribution of RPI Trends in Amboseli's surrounding lands") +
  tm_layout(legend.outside = TRUE)
```

```{r}
# Further Analysis
```

```{r}
## Grouping Study Area Information

Study.Area <- tibble::tibble(
  Area = c("TsavoEast", "TsavoWest", "Amboseli", "ChyuluHills",
           "NgaiNdethia", "SouthKitui", "AET.Conservancies", "AET.Buffers"),
  ProtectionType = c("NationalPark", "NationalPark", "NationalPark", "NationalPark",
                     "NationalReserve", "NationalReserve", "CommunityLand", "CommunityLand"))
```

```{r}
## Joining Governance Metadata to Pixel Level Slope Data

All.Pixel.Slopes <- All.Pixel.Slopes %>%
  left_join(Study.Area, by = "Area")

## Visualising Theil-Sen Slope Trends by Protection Type

ggplot(All.Pixel.Slopes, aes(x = ProtectionType, y = Slope, fill = ProtectionType)) +
  geom_violin(trim = FALSE, alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.5, color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "darkred") +
  labs(
    title = "Distribution of RPI Trends by Governance Type",
    x = "Governance Category",
    y = "TheilSen Slope"
  ) +
  scale_fill_brewer(palette = "Set2") +
  theme_beautiful()
```

```{r}
## Checking out Summary Statistics by Protection Type

Governance.Summary <- All.Pixel.Slopes %>%
  group_by(ProtectionType) %>%
  summarise(
    MeanSlope = mean(Slope, na.rm = TRUE),
    MedianSlope = median(Slope, na.rm = TRUE),
    SD = sd(Slope, na.rm = TRUE),
    N = sum(!is.na(Slope)),
    .groups = "drop"
  )

print(Governance.Summary)
```

```{r}
## Stats 1: Kruskal-Wallis Test

kruskal.test(Slope ~ ProtectionType, data = All.Pixel.Slopes)
```

```{r}
## Stats 2: Pairwise Wilcoxon Tests

pairwise.wilcox.test(All.Pixel.Slopes$Slope, All.Pixel.Slopes$ProtectionType, p.adjust.method = "bonferroni")
```

```{r}
# Temporal Trends across Years
```

```{r}
## Yearly summary data

# Combining all pixel values with area info
All.Pixel.Values <- bind_rows(
  Amboseli.RPI.Visual, TsavoEast.RPI.Visual, TsavoWest.RPI.Visual, ChyuluHills.RPI.Visual,
  NgaiNdethia.RPI.Visual, SouthKitui.RPI.Visual, AET.Conservancies.RPI.Visual, 
  AET.Buffers.RPI.Visual)

# Grouping by Year and Area to compute annual means
Annual.RPI.Trends <- All.Pixel.Values %>%
  group_by(Area, Year) %>%
  summarise(MeanRPI = mean(RPI_value, na.rm = TRUE), .groups = "drop")

# Visualising Annual RPI Trends

ggplot(Annual.RPI.Trends, aes(x = Year, y = MeanRPI, color = Area)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(title = "Annual Mean RPI Trends by Area", x = "Year", y = "Mean RPI") +
  scale_color_brewer(palette = "Set1") +
  theme(legend.position = "bottom") +
  theme_beautiful()
```

```{r}
## Zooming into the Areas of Primary Concern

Primary.Concern.Areas <- bind_rows(Amboseli.RPI.Visual, TsavoEast.RPI.Visual, TsavoWest.RPI.Visual, AET.Conservancies.RPI.Visual, AET.Buffers.RPI.Visual)

# Grouping by Year and Area to compute annual means
Primary.Concern.Areas.RPI.Trends <- Primary.Concern.Areas %>%
  group_by(Area, Year) %>%
  summarise(MeanRPI = mean(RPI_value, na.rm = TRUE), .groups = "drop")

    # "Primary.Concern.Areas.RPI.Trends" calculated the annual average RPI for each Area

# Visualising Annual RPI Trends for Primary Concern Areas
ggplot(Primary.Concern.Areas.RPI.Trends, aes(x = Year, y = MeanRPI, color = Area)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(title = "Annual Mean RPI Trends in Primary Concern Areas", x = "Year", y = "Mean RPI") +
  scale_color_brewer(palette = "Set1") +
  theme(legend.position = "bottom") +
  theme_beautiful()
```

```{r}
# Calculating Theil-Sen Slope for Primary Concern Areas

# Calculate slope & intercept for each area
Primary.TheilSen.Lines <- Primary.Concern.Areas.RPI.Trends %>%
  group_by(Area) %>%
  summarise(
    slope = sens.slope(MeanRPI)$estimates,
    intercept = mean(MeanRPI, na.rm = TRUE) - slope * mean(Year, na.rm = TRUE),
    .groups = "drop"
  )

# Plotting with "geom_line()" for dashed actual means & "geom_abline()" for TheilSen trends
ggplot(Primary.Concern.Areas.RPI.Trends, aes(x = Year, y = MeanRPI, color = Area)) + # Dashed annual trend lines
  geom_line(size = 1, linetype = "dashed") +
  # Points
  geom_point(size = 2) +
  # TheilSen trend lines manually
  geom_abline(data = Primary.TheilSen.Lines,
              aes(slope = slope, intercept = intercept, color = Area),
              linetype = "solid", linewidth = 1.2, show.legend = FALSE) +
  labs(title = "Annual Mean RPI Trends (dashed lines) with TheilSen Lines (straight lines)",x = "Year", y = "Mean RPI") +
  scale_color_brewer(palette = "Set1") +
  theme_beautiful() +
  theme(legend.position = "right")

```

```{r}
# Stastistical Analysis of Temporal Trends

# Fitting a linear model

lm_test <- lm(MeanRPI ~ Year * Area, data = Primary.Concern.Areas.RPI.Trends)
anova(lm_test)
summary(lm_test)
```

```{r}
## Explanation of Results above:
# The ANOVA results indicate whether there are significant differences in RPI trends across different areas and years.

# The summary provides coefficients for the linear model, showing how RPI changes with each year and area.

  # Area is highly significant (p < 0.001)  Different areas have different mean RPI levels.

  # Year is not significant  No overall temporal trend across all areas.

  # Year  Area is not significant (but close at p = 0.127)  Trend differences across areas are not statistically strong, but there are hints that Tsavo East is rising faster (Year:AreaTsavoEast is significant).
```

```{r}
# Mapping Per-Pixel Slope for the Primary Concern Areas


tmap_mode("view")  # placed "view" in stead of "plot" for interactiveness

tmap_arrange(
  tm_shape(Amboseli.Slope.Raster) +
    tm_raster(
      col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
      col.legend = tm_legend(title = "Slope", reverse = TRUE)) +
    tm_title("Amboseli"),

  tm_shape(TsavoEast.Slope.Raster) +
    tm_raster(
      col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
      col.legend = tm_legend(title = "Slope", reverse = TRUE)) +
    tm_title("Tsavo East"),

  tm_shape(TsavoWest.Slope.Raster) +
    tm_raster(
      col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
      col.legend = tm_legend(title = "Slope", reverse = TRUE))+
    tm_title("Tsavo West"),

  tm_shape(AET.AllZones.Slope.Raster) +
    tm_raster(
      col.scale = tm_scale_continuous(values = "pu_or", midpoint = 0),
      col.legend = tm_legend(title = "Slope", reverse = TRUE)) +
    tm_title("Amboseli Surrounding Lands"),

  ncol = 2, nrow = 2)


  # Saving the maps as a PNG file
    # tmap_save(filename = "RPI_Slope_Maps_ConcernAreas.png", width = 10, height = 8, dpi = 300)
```

```{r}
# 5-Year rolling Mean of RPI Trends

  # 1. Calculate the 5-year rolling mean for each 'Area'
    # This is crucial: group_by(Area) before applying slide_dbl

Primary.Concern.Areas.RPI.Trends.5yr <- Primary.Concern.Areas.RPI.Trends %>%
  mutate(Year = as.numeric(Year)) %>% # Ensures Year is numeric & Grouping by Area so the rolling mean is calculated independently for each area
  group_by(Area) %>%
  # Arranging by year within each group to ensure correct rolling window calculation
  arrange(Year) %>%
  mutate(
    Rolling_Mean_RPI = slide_dbl(
      .x = MeanRPI,  # Apply rolling mean to the annual mean RPI
      .f = mean,
      .before = 4,  # Current year + 4 previous years = 5 years
      .after = 0,
      .complete = TRUE # Only calculate for full 5-year windows (eg: Years starts in 2000, its Rolling_Mean_RPI will be NA for 2000, 2001, 2002, and 2003. The first non-NA value will be for 2004 (which averages 2000-2004).)
    )
  ) %>%
  ungroup() # Ungrouping after calculation as I don't need grouping for subsequent steps
```

```{r}
# Visualising 5-Year Rolling Mean RPI Trends for Primary Concern Areas

ggplot(Primary.Concern.Areas.RPI.Trends.5yr, aes(x = Year, y = Rolling_Mean_RPI, color = Area)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  labs(title = "5-Year Rolling Mean RPI Trends in Primary Concern Areas",
    x = "Year (End of 5-Year Window)", # Adjust label for clarity
    y = "5-Year Rolling Mean RPI") +
  scale_color_brewer(palette = "Set1") +
  theme(legend.position = "bottom") +
  theme_beautiful() +
  
  # This is to adjust x-axis breaks to avoid clutter, especially if years are dense
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) # Adjust n as needed for number of labels
```

```{r}
# Creating a Violin Plot for 5-Year Rolling Mean RPI Trends

# Reorder Area by descending median Rolling_Mean_RPI
Primary.Concern.Areas.RPI.Trends.5yr <- Primary.Concern.Areas.RPI.Trends.5yr %>%
  mutate(Area = factor(Area, levels = names(sort(tapply(Rolling_Mean_RPI, Area, median, na.rm = TRUE), decreasing = TRUE))))

# Then to plot the violin plot
ggplot(Primary.Concern.Areas.RPI.Trends.5yr, aes(x = Area, y = Rolling_Mean_RPI, fill = Area)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA, color = "black") +
  labs(title = "Distribution of 5-Year Rolling Mean RPI Trends by Area",
    x = "Area", y = "5-Year Rolling Mean RPI") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme_beautiful() +
  
  # Adjusting the fill colors for better visibility
  scale_fill_brewer(palette = "Set2")
```

```{r}
# Temporal Performance Overview
```

```{r}
## Import 

Temporal.Performance <- rast("C:/BIOM4009 ResearchProject/DATA/Geospatial Data/R Use/2.Kenya-s-Rangelands-Protected-Areas_files/RPI Datasets (GuyLomax)/rpi_ea_temporal_performance.tif")
```

```{r}
## Clipping Temporal Performance to Kenya Admin Boundary

### Ensure CRS matches
Kenya.Admin.Boundary <- st_transform(Kenya.Admin.Boundary, crs(Temporal.Performance))

### Convert to terra vector
Kenya.Admin.Boundary.Vect <- vect(Kenya.Admin.Boundary)

### Crop and mask
Temporal.Performance.Kenya <- crop(Temporal.Performance, Kenya.Admin.Boundary.Vect)
Temporal.Performance.Kenya <- mask(Temporal.Performance.Kenya, Kenya.Admin.Boundary.Vect)
```

```{r}
##  Plotting Temporal Performance clipped to Kenya's Administrative Boundary

ggplot() +
  geom_spatraster(data = Temporal.Performance.Kenya) +
  facet_wrap(~lyr, ncol = 3) +
  scale_fill_gradientn(
    colours = c("lightblue", "limegreen", "yellow", "red"),
    na.value = "grey90"
  ) +
  geom_sf(data = Kenya.Admin.Boundary, fill = NA, color = "black", linewidth = 0.3) +
  labs(
    title = "Temporal Performance over Kenya",
    subtitle = "MAE, RMSE, and R metrics",
    fill = "Performance"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",
    strip.text = element_text(face = "bold", size = 12),
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  )
```

```{r}
## Extracting RSQ values from the raster & linking to each RPI.Mean
## Extract R layer

RSQ.Layer <- Temporal.Performance[["rsq"]]
```

```{r}
# Check alignment for Amboseli  they should match in extent/resolution

all.equal(ext(RSQ.Layer), ext(Amboseli.RPI.Mean))  # should return TRUE
```

```{r}
# The above mean relative difference of 0.2704655 informs me that the Rasters are not aligned
```

```{r}
# Step 1: Ensure the CRS is the same in Amboseli
crs(RSQ.Layer) == crs(Amboseli.RPI.Mean)  # Should be TRUE
```

```{r}
# Step 2: Align extent and resolution  resample R to match RPI mean raster in Amboseli
RSQ.Resampled.Amboseli <- resample(RSQ.Layer, Amboseli.RPI.Mean, method = "bilinear")
```

```{r}
# Step 3: Now try checking again in Amboseli
all.equal(ext(RSQ.Resampled.Amboseli), ext(Amboseli.RPI.Mean))  # Should now be TRUE
```

```{r}
# Check alignment  they should match in extent/resolution in TsavoEast
all.equal(ext(RSQ.Layer), ext(TsavoEast.RPI.Mean))  # should return TRUE
```

```{r}
# The above mean relative difference of 0.2447468 informs me that the Rasters are not aligned
```

```{r}
# Step 1: Ensure the CRS is the same in TsavoEast
crs(RSQ.Layer) == crs(TsavoEast.RPI.Mean)  # Should be TRUE
```

```{r}
# Step 2: Align extent and resolution  resample R to match RPI mean raster in TsavoEast
RSQ.Resampled.TsavoEast <- resample(RSQ.Layer, TsavoEast.RPI.Mean, method = "bilinear")
```

```{r}
# Step 3: Now try checking again in TsavoEast
all.equal(ext(RSQ.Resampled.TsavoEast), ext(TsavoEast.RPI.Mean))  # Should now be TRUE
```

```{r}
# Check alignment  they should match in extent/resolution in TsavoWest
all.equal(ext(RSQ.Layer), ext(TsavoWest.RPI.Mean))  # should return TRUE
```

```{r}
# The above mean relative difference of 0.2509435 informs me that the Rasters are not aligned
```

```{r}
# Step 1: Ensure the CRS is the same in TsavoWest
crs(RSQ.Layer) == crs(TsavoWest.RPI.Mean)  # Should be TRUE
```

```{r}
# Step 2: Align extent and resolution  resample R to match RPI mean raster in TsavoWest
RSQ.Resampled.TsavoWest <- resample(RSQ.Layer, TsavoWest.RPI.Mean, method = "bilinear")
```

```{r}
# Step 3: Now try checking again for TsavoWest
all.equal(ext(RSQ.Resampled.TsavoWest), ext(TsavoWest.RPI.Mean))  # Should now be TRUE
```

```{r}
# Check alignment  they should match in extent/resolution in AET.Conservancies
all.equal(ext(RSQ.Layer), ext(AET.Conservancies.RPI.Mean))  # should return TRUE
```

```{r}
# The above mean relative difference of 0.2535526 informs me that the Rasters are not aligned
```

```{r}
# Step 1: Ensure the CRS is the same in AET.Conservancies
crs(RSQ.Layer) == crs(AET.Conservancies.RPI.Mean)  # Should be TRUE
```

```{r}
# Step 2: Align extent and resolution  resample R to match RPI mean raster in AET.Conservancies
RSQ.Resampled.AET.Conservancies <- resample(RSQ.Layer, AET.Conservancies.RPI.Mean, method = "bilinear")
```

```{r}
# Step 3: Now try checking again
all.equal(ext(RSQ.Resampled.AET.Conservancies), ext(AET.Conservancies.RPI.Mean))  # Should now be TRUE
```

```{r}
# Check alignment  they should match in extent/resolution in AET.Buffers
all.equal(ext(RSQ.Layer), ext(AET.Buffers.RPI.Mean))  # should return TRUE
```

```{r}
# The above mean relative difference of 0.2540185 informs me that the Rasters are not aligned
```

```{r}
# Step 1: Ensure the CRS is the same in AET.Buffers
crs(RSQ.Layer) == crs(AET.Buffers.RPI.Mean)  # Should be TRUE
```

```{r}
# Step 2: Align extent and resolution  resample R to match RPI mean raster in AET.Buffers
RSQ.Resampled.AET.Buffers <- resample(RSQ.Layer, AET.Buffers.RPI.Mean, method = "bilinear")
```

```{r}
# Step 3: Now try checking again
all.equal(ext(RSQ.Resampled.AET.Buffers), ext(AET.Buffers.RPI.Mean))  # Should now be TRUE
```

```{r}
# Check alignment  they should match in extent/resolution
all.equal(ext(RSQ.Layer), ext(AET.AllZones.RPI.Mean))  # should return TRUE
```

```{r}
# The above mean relative difference of 0.252714 informs me that the Rasters are not aligned
```

```{r}
# Step 1: Ensure the CRS is the same in AET.AllZones
crs(RSQ.Layer) == crs(AET.AllZones.RPI.Mean)  # Should be TRUE
```

```{r}
# Step 2: Align extent and resolution  resample R to match RPI mean raster
RSQ.Resampled.AET.AllZones <- resample(RSQ.Layer, AET.AllZones.RPI.Mean, method = "bilinear")
```

```{r}
# Step 3: Now try checking again
all.equal(ext(RSQ.Resampled.AET.AllZones), ext(AET.AllZones.RPI.Mean))  # Should now be TRUE
```

```{r}
## Mask RPI rasters using R threshold

# #  Set R threshold
RSQ.Threshold.3 <- 0.3  # I will adjust this to 0.1 or 0.2 after discussions with Guy Lomax

# 1. Creating mask for pixels with R >= threshold
RSQ.Mask.Amboseli <- RSQ.Resampled.Amboseli >= RSQ.Threshold.3

# 2. Applying the mask to the RPI mean raster
Amboseli.RPI.Mean.Filtered.3 <- mask(Amboseli.RPI.Mean, RSQ.Mask.Amboseli, maskvalues = FALSE)

# 2. Visualising the filtered result
tmap_mode("view")
tm_shape(Amboseli.RPI.Mean.Filtered.3) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.3)", reverse = TRUE)) +
  tm_shape(Amboseli) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# Repeating the masking process for other areas

# Creating mask for pixels with R >= threshold
RSQ.Mask.TsavoEast <- RSQ.Resampled.TsavoEast >= RSQ.Threshold.3

# Applying the mask to the RPI mean raster
TsavoEast.RPI.Mean.Filtered.3 <- mask(TsavoEast.RPI.Mean, RSQ.Mask.TsavoEast, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(TsavoEast.RPI.Mean.Filtered.3) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.3)", reverse = TRUE)) +
  tm_shape(TsavoEast) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# Creating mask for pixels with R >= threshold
RSQ.Mask.TsavoWest <- RSQ.Resampled.TsavoWest >= RSQ.Threshold.3

# Applying the mask to the RPI mean raster
TsavoWest.RPI.Mean.Filtered.3 <- mask(TsavoWest.RPI.Mean, RSQ.Mask.TsavoWest, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(TsavoWest.RPI.Mean.Filtered.3) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.3)", reverse = TRUE)) +
  tm_shape(TsavoWest) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# Creating mask for pixels with R >= threshold
RSQ.Mask.AET.Conservancies <- RSQ.Resampled.AET.Conservancies >= RSQ.Threshold.3

# Applying the mask to the RPI mean raster
AET.Conservancies.RPI.Mean.Filtered.3 <- mask(AET.Conservancies.RPI.Mean, RSQ.Mask.AET.Conservancies, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(AET.Conservancies.RPI.Mean.Filtered.3) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.3)", reverse = TRUE)) +
  tm_shape(AET.Conservancies) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# Creating mask for pixels with R >= threshold
RSQ.Mask.AET.Buffers <- RSQ.Resampled.AET.Buffers >= RSQ.Threshold.3

# Applying the mask to the RPI mean raster
AET.Buffers.RPI.Mean.Filtered.3 <- mask(AET.Buffers.RPI.Mean, RSQ.Mask.AET.Buffers, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(AET.Buffers.RPI.Mean.Filtered.3) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.3)", reverse = TRUE)) +
  tm_shape(AET.Buffers) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# Creating mask for pixels with R >= threshold
RSQ.Mask.AET.AllZones <- RSQ.Resampled.AET.AllZones >= RSQ.Threshold.3

# Applying the mask to the RPI mean raster
AET.AllZones.RPI.Mean.Filtered.3 <- mask(AET.AllZones.RPI.Mean, RSQ.Mask.AET.AllZones, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(AET.AllZones.RPI.Mean.Filtered.3) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.3)", reverse = TRUE)) +
  tm_shape(AET.AllZones) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Comparing the maps side by side

tmap_mode("view")  # Sets plot to interactive mode

tmap_arrange(
  tm_shape(Amboseli.RPI.Mean.Filtered.3) +
    tm_raster(col.legend = tm_legend(title = "Amboseli Mean RPI(R  0.3)")), # Updated title
  tm_shape(TsavoEast.RPI.Mean.Filtered.3) +
    tm_raster(col.legend = tm_legend(title = "Tsavo East Mean RPI(R  0.3)")), # Updated title
  tm_shape(TsavoWest.RPI.Mean.Filtered.3) +
    tm_raster(col.legend = tm_legend(title = "Tsavo West Mean RPI(R  0.3)")), # Updated title
  tm_shape(AET.AllZones.RPI.Mean.Filtered.3) +
    tm_raster(col.legend = tm_legend(title = "AET All Zones Mean RPI(R  0.3)")), # Updated title
  ncol = 2
)
```

```{r}
# # Test Statistics for Filtered (0.3 R^2 threshold) RPI Maps
```

```{r}
# 1. Amboseli

# Extract values from both rasters into a data.frame
Amboseli.Values.RPI.Rsquare.Filtered.3 <- as.data.frame(c(Amboseli.RPI.Mean.Filtered.3, RSQ.Resampled.Amboseli), na.rm = TRUE)

# Rename for clarity
colnames(Amboseli.Values.RPI.Rsquare.Filtered.3) <- c("RPI", "RSQ")
```

```{r}
# 2. TsavoEast

# Extract values from both rasters into a data.frame
TsavoEast.Values.RPI.Rsquare.Filtered.3 <- as.data.frame(c(TsavoEast.RPI.Mean.Filtered.3, RSQ.Resampled.TsavoEast), na.rm = TRUE)

# Rename for clarity
colnames(TsavoEast.Values.RPI.Rsquare.Filtered.3) <- c("RPI", "RSQ")
```

```{r}
# 3. TsavoWest

# Extract values from both rasters into a data.frame
TsavoWest.Values.RPI.Rsquare.Filtered.3 <- as.data.frame(c(TsavoWest.RPI.Mean.Filtered.3, RSQ.Resampled.TsavoWest), na.rm = TRUE)

# Rename for clarity
colnames(TsavoWest.Values.RPI.Rsquare.Filtered.3) <- c("RPI", "RSQ")
```

```{r}
# 4. AET.Conservancies

# Extract values from both rasters into a data.frame
AET.Conservancies.Values.RPI.Rsquare.Filtered.3 <- as.data.frame(c(AET.Conservancies.RPI.Mean.Filtered.3, RSQ.Resampled.AET.Conservancies), na.rm = TRUE)

# Rename for clarity
colnames(AET.Conservancies.Values.RPI.Rsquare.Filtered.3) <- c("RPI", "RSQ")
```

```{r}
# 5. AET.Buffers

# Extract values from both rasters into a data.frame
AET.Buffers.Values.RPI.Rsquare.Filtered.3 <- as.data.frame(c(AET.Buffers.RPI.Mean.Filtered.3, RSQ.Resampled.AET.Buffers), na.rm = TRUE)

# Rename for clarity
colnames(AET.Buffers.Values.RPI.Rsquare.Filtered.3) <- c("RPI", "RSQ")
```

```{r}
# 6. AET.AllZones

# Extract values from both rasters into a data.frame
AET.AllZones.Values.RPI.Rsquare.Filtered.3 <- as.data.frame(c(AET.AllZones.RPI.Mean.Filtered.3, RSQ.Resampled.AET.AllZones), na.rm = TRUE)

# Rename for clarity
colnames(AET.AllZones.Values.RPI.Rsquare.Filtered.3) <- c("RPI", "RSQ")
```

```{r}
# #Plotting the R and RPI values for each area
```

```{r}
# 1. Amboseli 

Amboseli.Values.RPI.Rsquare.Filtered.3.Plot <- ggplot(Amboseli.Values.RPI.Rsquare.Filtered.3, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Amboseli",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

Amboseli.Values.RPI.Rsquare.Filtered.3.Plot
```

```{r}
# 2. TsavoEast

TsavoEast.Values.RPI.Rsquare.Filtered.3.Plot <- ggplot(TsavoEast.Values.RPI.Rsquare.Filtered.3, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Tsavo East",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

TsavoEast.Values.RPI.Rsquare.Filtered.3.Plot
```

```{r}
# 3. TsavoWest

TsavoWest.Values.RPI.Rsquare.Filtered.3.Plot <- ggplot(TsavoWest.Values.RPI.Rsquare.Filtered.3, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Tsavo West",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

TsavoWest.Values.RPI.Rsquare.Filtered.3.Plot
```

```{r}
# 4. AET.Conservancies

AET.Conservancies.Values.RPI.Rsquare.Filtered.3.Plot <- ggplot(AET.Conservancies.Values.RPI.Rsquare.Filtered.3, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Amboseli surrounding Conservancies",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

AET.Conservancies.Values.RPI.Rsquare.Filtered.3.Plot
```

```{r}
# 5. AET.Buffers

AET.Buffers.Values.RPI.Rsquare.Filtered.3.Plot <- ggplot(AET.Buffers.Values.RPI.Rsquare.Filtered.3, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Amboseli surrounding Grazelands",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

AET.Buffers.Values.RPI.Rsquare.Filtered.3.Plot
```

```{r}
# 6. AET.AllZones

AET.AllZones.Values.RPI.Rsquare.Filtered.3.Plot <- ggplot(AET.AllZones.Values.RPI.Rsquare.Filtered.3, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Amboseli Surrounding Lands",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

AET.AllZones.Values.RPI.Rsquare.Filtered.3.Plot
```

```{r}
# # Combining all the plots together

All.RPI.Rsquare.Filtered.3.Plots <- 
  (Amboseli.Values.RPI.Rsquare.Filtered.3.Plot | TsavoEast.Values.RPI.Rsquare.Filtered.3.Plot | TsavoWest.Values.RPI.Rsquare.Filtered.3.Plot) /
  (AET.Conservancies.Values.RPI.Rsquare.Filtered.3.Plot | AET.Buffers.Values.RPI.Rsquare.Filtered.3.Plot | AET.AllZones.Values.RPI.Rsquare.Filtered.3.Plot)

# Show the combined plot
All.RPI.Rsquare.Filtered.3.Plots
```

```{r}
# # Feedback on the above!

# In several zones, notably AET.Conservancies, Amboseli, and AET.AllZones, there are observed clusters of pixels with consistently low RPI values (e.g., < 0.5) and strongly negative R values (e.g., < -1). This combination suggests that the quantile regression forest model systematically overestimates inter-annual GPP variability in areas with consistently low productivity, such as rocky or sparsely vegetated regions. In these cases, the null model (assuming constant GPP) outperforms the predictive model, leading to highly negative R values. As such, these areas are likely unsuitable for interpreting RPI trends, and we exclude them from further analysis by masking out pixels with R < 0.
```

```{r}
# # Masking out Pixels with Negative R^2 (RPI pixels where R < 0.1)

# #  Set R threshold
RSQ.Threshold.1 <- 0.1  # After agreement with Guy that "Any positive R-squared should be an improvement on using raw GPP or NDVI data"
```

```{r}
# 1. Amboseli
 
RSQ.Mask.Amboseli <- RSQ.Resampled.Amboseli >= RSQ.Threshold.1

# Applying Mask to RPI Mean Raster
Amboseli.RPI.Mean.Filtered.1 <- mask(Amboseli.RPI.Mean, RSQ.Mask.Amboseli, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(Amboseli.RPI.Mean.Filtered.1) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.1)", reverse = TRUE)) +
  tm_shape(Amboseli) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# 2. Tsavo East

# Step 1: Mask out RPI pixels where R < 0.1
RSQ.Mask.TsavoEast <- RSQ.Resampled.TsavoEast >= RSQ.Threshold.1

# Applying Mask to RPI Mean Raster
TsavoEast.RPI.Mean.Filtered.1 <- mask(TsavoEast.RPI.Mean, RSQ.Mask.TsavoEast, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(TsavoEast.RPI.Mean.Filtered.1) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.1)", reverse = TRUE)) +
  tm_shape(TsavoEast) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# 3. Tsavo West

# Step 1: Mask out RPI pixels where R < 0.1
RSQ.Mask.TsavoWest <- RSQ.Resampled.TsavoWest >= RSQ.Threshold.1

# Applying Mask to RPI Mean Raster
TsavoWest.RPI.Mean.Filtered.1 <- mask(TsavoWest.RPI.Mean, RSQ.Mask.TsavoWest, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(TsavoWest.RPI.Mean.Filtered.1) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.1)", reverse = TRUE)) +
  tm_shape(TsavoWest) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
#4. Amboseli Surrounding Conservancies

# Step 1: Mask out RPI pixels where R < 0.1
RSQ.Mask.AET.Conservancies <- RSQ.Resampled.AET.Conservancies >= RSQ.Threshold.1

# Applying Mask to RPI Mean Raster
AET.Conservancies.RPI.Mean.Filtered.1 <- mask(AET.Conservancies.RPI.Mean, RSQ.Mask.AET.Conservancies, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(AET.Conservancies.RPI.Mean.Filtered.1) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.1)", reverse = TRUE)) +
  tm_shape(AET.Conservancies) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# 5. Amboseli Surrounding Grazelands

# Step 1: Mask out RPI pixels where R < 0.1
RSQ.Mask.AET.Buffers <- RSQ.Resampled.AET.Buffers >= RSQ.Threshold.1

# Applying Mask to RPI Mean Raster
AET.Buffers.RPI.Mean.Filtered.1 <- mask(AET.Buffers.RPI.Mean, RSQ.Mask.AET.Buffers, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(AET.Buffers.RPI.Mean.Filtered.1) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.1)", reverse = TRUE)) +
  tm_shape(AET.Buffers) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
# 6. Amboseli Surrounding Lands

# Step 1: Mask out RPI pixels where R < 0.1
RSQ.Mask.AET.AllZones <- RSQ.Resampled.AET.AllZones >= RSQ.Threshold.1

# Applying Mask to RPI Mean Raster
AET.AllZones.RPI.Mean.Filtered.1 <- mask(AET.AllZones.RPI.Mean, RSQ.Mask.AET.AllZones, maskvalues = FALSE)

# Visualising the filtered result
tmap_mode("view")
tm_shape(AET.AllZones.RPI.Mean.Filtered.1) +
  tm_raster(
    col.scale = tm_scale_continuous(values = "viridis"), 
    col.legend = tm_legend(title = "Mean RPI (Filtered by R  0.1)", reverse = TRUE)) +
  tm_shape(AET.AllZones) +
  tm_borders(col = "white", lwd = 2) +
  tm_layout(legend.outside = TRUE)
```

```{r}
## Comparing the maps side by side

tmap_mode("view")  # Sets plot to interactive mode

tmap_arrange(
  tm_shape(Amboseli.RPI.Mean.Filtered.1) +
    tm_raster(col.legend = tm_legend(title = "Amboseli Mean RPI(R  0.1)")), # Updated title
  tm_shape(TsavoEast.RPI.Mean.Filtered.1) +
    tm_raster(col.legend = tm_legend(title = "Tsavo East Mean RPI(R  0.1)")), # Updated title
  tm_shape(TsavoWest.RPI.Mean.Filtered.1) +
    tm_raster(col.legend = tm_legend(title = "Tsavo West Mean RPI(R  0.1)")), # Updated title
  tm_shape(AET.AllZones.RPI.Mean.Filtered.1) +
    tm_raster(col.legend = tm_legend(title = "AET All Zones Mean RPI(R  0.1)")), # Updated title
  ncol = 2
)
```

```{r}
# # Test Statistics for Filtered (0.1 R^2 threshold) RPI Maps
```

```{r}
# 1. Amboseli

# Extract values from both rasters into a data.frame
Amboseli.Values.RPI.Rsquare.Filtered.1 <- as.data.frame(c(Amboseli.RPI.Mean.Filtered.1, RSQ.Resampled.Amboseli), na.rm = TRUE)

# Rename for clarity
colnames(Amboseli.Values.RPI.Rsquare.Filtered.1) <- c("RPI", "RSQ")
```

```{r}
# 2. TsavoEast

# Extract values from both rasters into a data.frame
TsavoEast.Values.RPI.Rsquare.Filtered.1 <- as.data.frame(c(TsavoEast.RPI.Mean.Filtered.1, RSQ.Resampled.TsavoEast), na.rm = TRUE)

# Rename for clarity
colnames(TsavoEast.Values.RPI.Rsquare.Filtered.1) <- c("RPI", "RSQ")
```

```{r}
# 3. TsavoWest

# Extract values from both rasters into a data.frame
TsavoWest.Values.RPI.Rsquare.Filtered.1 <- as.data.frame(c(TsavoWest.RPI.Mean.Filtered.1, RSQ.Resampled.TsavoWest), na.rm = TRUE)

# Rename for clarity
colnames(TsavoWest.Values.RPI.Rsquare.Filtered.1) <- c("RPI", "RSQ")
```

```{r}
# 4. AET.Conservancies

# Extract values from both rasters into a data.frame
AET.Conservancies.Values.RPI.Rsquare.Filtered.1 <- as.data.frame(c(AET.Conservancies.RPI.Mean.Filtered.1, RSQ.Resampled.AET.Conservancies), na.rm = TRUE)

# Rename for clarity
colnames(AET.Conservancies.Values.RPI.Rsquare.Filtered.1) <- c("RPI", "RSQ")
```

```{r}
# 5. AET.Buffers

# Extract values from both rasters into a data.frame
AET.Buffers.Values.RPI.Rsquare.Filtered.1 <- as.data.frame(c(AET.Buffers.RPI.Mean.Filtered.1, RSQ.Resampled.AET.Buffers), na.rm = TRUE)

# Rename for clarity
colnames(AET.Buffers.Values.RPI.Rsquare.Filtered.1) <- c("RPI", "RSQ")
```

```{r}
# 6. AET.AllZones

# Extract values from both rasters into a data.frame
AET.AllZones.Values.RPI.Rsquare.Filtered.1 <- as.data.frame(c(AET.AllZones.RPI.Mean.Filtered.1, RSQ.Resampled.AET.AllZones), na.rm = TRUE)

# Rename for clarity
colnames(AET.AllZones.Values.RPI.Rsquare.Filtered.1) <- c("RPI", "RSQ")
```

```{r}
# #Plotting the R and RPI values for each area
```

```{r}
# 1. Amboseli 

Amboseli.Values.RPI.Rsquare.Filtered.1.Plot <- ggplot(Amboseli.Values.RPI.Rsquare.Filtered.1, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Amboseli",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

Amboseli.Values.RPI.Rsquare.Filtered.1.Plot
```

```{r}
# 2. TsavoEast

TsavoEast.Values.RPI.Rsquare.Filtered.1.Plot <- ggplot(TsavoEast.Values.RPI.Rsquare.Filtered.1, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Tsavo East",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

TsavoEast.Values.RPI.Rsquare.Filtered.1.Plot
```

```{r}
# 3. TsavoWest

TsavoWest.Values.RPI.Rsquare.Filtered.1.Plot <- ggplot(TsavoWest.Values.RPI.Rsquare.Filtered.1, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Tsavo West",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

TsavoWest.Values.RPI.Rsquare.Filtered.1.Plot
```

```{r}
# 4. AET.Conservancies

AET.Conservancies.Values.RPI.Rsquare.Filtered.1.Plot <- ggplot(AET.Conservancies.Values.RPI.Rsquare.Filtered.3, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Amboseli surrounding Conservancies",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

AET.Conservancies.Values.RPI.Rsquare.Filtered.1.Plot
```

```{r}
# 5. AET.Buffers

AET.Buffers.Values.RPI.Rsquare.Filtered.1.Plot <- ggplot(AET.Buffers.Values.RPI.Rsquare.Filtered.1, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Amboseli surrounding Grazelands",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

AET.Buffers.Values.RPI.Rsquare.Filtered.1.Plot
```

```{r}
# 6. AET.AllZones

AET.AllZones.Values.RPI.Rsquare.Filtered.1.Plot <- ggplot(AET.AllZones.Values.RPI.Rsquare.Filtered.1, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 40) +  # increase bins for more granularity
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +  # log scale helps distinguish dense areas
  labs(
    title = "RPI vs R: Amboseli Surrounding Lands",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_beautiful() +
  theme(legend.position = "right")

AET.AllZones.Values.RPI.Rsquare.Filtered.1.Plot
```

```{r}
# # Combining all the plots together

All.RPI.Rsquare.Filtered.1.Plots <- 
  (Amboseli.Values.RPI.Rsquare.Filtered.1.Plot | TsavoEast.Values.RPI.Rsquare.Filtered.1.Plot | TsavoWest.Values.RPI.Rsquare.Filtered.1.Plot) /
  (AET.Conservancies.Values.RPI.Rsquare.Filtered.1.Plot | AET.Buffers.Values.RPI.Rsquare.Filtered.1.Plot | AET.AllZones.Values.RPI.Rsquare.Filtered.1.Plot)

# Show the combined plot
All.RPI.Rsquare.Filtered.1.Plots
```

```{r}
# # Clip RPI & R to Kenya
```

```{r}
# First, calculate the mean RPI across all years
RPI.Mean.EA <- app(RPI, mean, na.rm = TRUE)

# Crop and mask both layers to Kenya
RPI.Mean.Kenya <- mask(crop(RPI.Mean.EA, Kenya.Admin.Boundary), Kenya.Admin.Boundary)

RSQ.Kenya <- mask(crop(RSQ.Layer, Kenya.Admin.Boundary), Kenya.Admin.Boundary)
```

```{r}
# Convert to Data Frame

Kenya.Values.RPI.Rsquare <- as.data.frame(
  c(RPI = RPI.Mean.Kenya, RSQ = RSQ.Kenya),
  na.rm = TRUE
)
colnames(Kenya.Values.RPI.Rsquare) <- c("RPI", "RSQ")
```

```{r}
# Plotting with red Threshold line

Kenya.RPI.Rsquare.Plot <- ggplot(Kenya.Values.RPI.Rsquare, aes(x = RSQ, y = RPI)) +
  geom_hex(bins = 50) +
  scale_fill_viridis_c(option = "D", trans = "log10", name = "Density") +
  geom_vline(xintercept = 0.1, linetype = "dashed", color = "red", size = 1) +
  labs(
    title = "RPI vs R across Kenya (Before Filtering)",
    subtitle = "Red dashed line = R threshold (0.1)",
    x = expression(R^2 ~ "(Model Performance)"),
    y = "Mean RPI"
  ) +
  theme_minimal()

Kenya.RPI.Rsquare.Plot
```

```{r}
# # Map Pixels with R  0.1 in Kenya (A poor model fit filtering out poor-quality predictions)

# --- CREATE RSQ.Low.Performance.Mask ---
# Method 1: Logical Mask (Recommended for simplicity)
# Pixels where RSQ.Kenya <= 0.1 will be TRUE, others will be FALSE.
# tmap handles logical rasters very well.
RSQ.Low.Performance.Mask <- RSQ.Kenya <= 0.1

# Method 2: Numeric Mask (If you prefer 1s and NAs explicitly) & this creates a raster where pixels <= 0.1 are 1, and > 0.1 become NA.
    # RSQ.Low.Performance.Mask <- classify(RSQ.Kenya, rcl = matrix(c(-Inf, 0.1, 1, 0.1, Inf, NA), ncol = 3, byrow = TRUE))
# Or
    # RSQ.Low.Performance.Mask <- app(RSQ.Kenya, fun = function(x) { ifelse(x <= 0.1, 1, NA) })
```

```{r}
# Plotting the Masked Layer

tmap_mode("view")

tm_shape(RSQ.Low.Performance.Mask) +
  tm_raster(
    # tmap will automatically use the single layer for 'col'.
    # We define the discrete scale based on internal 0/1 representation of TRUE/FALSE.
    col.scale = tm_scale_discrete(
      # Map 0 (representing FALSE) to NA (transparent).
      # Map 1 (representing TRUE) to "red".
      values = c("0" = NA, "1" = "red"),

      # Labels for the legend.
      # An empty string "" for the first entry (corresponding to 0/FALSE)
      # will make it invisible in the legend, showing only the red category.
      labels = c("", expression(R^2 ~ " 0.1")),
      show.na = FALSE # Ensures any actual NA values in the raster are not shown in the legend
    ),
    col_alpha = 0.6, # Transparency for the red areas
    col.legend = tm_legend(title = "Poor Model Fit"), # Title for the legend box
    legend.show = TRUE # Make sure the legend is displayed
  ) +
  tm_shape(Kenya.Admin.Boundary) +
  tm_borders(col = "black") +
  tm_layout(
    legend.outside = TRUE # Place the legend outside the map area
  ) +
  tm_title("Pixels with Poor Model Fit (R  0.1) in Kenya") # Main title for the map
```

```{r}

